

/*
 * Document Service
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.document.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cnsmodules.document.model.DocumentPostResponseValueAdminData;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * DocumentPostResponseValue
 */

// CHECKSTYLE:OFF
public class DocumentPostResponseValue 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private UUID id;

  @JsonProperty("title")
  private String title;

  @JsonProperty("fileName")
  private String fileName;

  @JsonProperty("category")
  private String category;

  @JsonProperty("status")
  private String status;

  @JsonProperty("thumbnailStatus")
  private String thumbnailStatus;

  @JsonProperty("type")
  private String type;

  @JsonProperty("fileSize")
  private String fileSize;

  @JsonProperty("uploadUrl")
  private String uploadUrl;

  @JsonProperty("adminData")
  private DocumentPostResponseValueAdminData adminData;

  @JsonProperty("hostObjectId")
  private UUID hostObjectId;

  @JsonProperty("hostObjectType")
  private String hostObjectType;

  @JsonProperty("icon")
  private String icon;

  @JsonProperty("color")
  private String color;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param id  The id of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue id(@Nonnull final UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id  The id of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public UUID getId() {
    return id;
  }

  /**
  * Set the id of this {@link DocumentPostResponseValue} instance.
  *
  * @param id  The id of this {@link DocumentPostResponseValue}
  */
  public void setId( @Nonnull final UUID id) {
    this.id = id;
  }

   /**
   * Set the title of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param title  The title of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue title(@Nonnull final String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title  The title of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getTitle() {
    return title;
  }

  /**
  * Set the title of this {@link DocumentPostResponseValue} instance.
  *
  * @param title  The title of this {@link DocumentPostResponseValue}
  */
  public void setTitle( @Nonnull final String title) {
    this.title = title;
  }

   /**
   * Set the fileName of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param fileName  The fileName of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue fileName(@Nonnull final String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName  The fileName of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getFileName() {
    return fileName;
  }

  /**
  * Set the fileName of this {@link DocumentPostResponseValue} instance.
  *
  * @param fileName  The fileName of this {@link DocumentPostResponseValue}
  */
  public void setFileName( @Nonnull final String fileName) {
    this.fileName = fileName;
  }

   /**
   * Set the category of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param category  The category of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue category(@Nonnull final String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category  The category of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getCategory() {
    return category;
  }

  /**
  * Set the category of this {@link DocumentPostResponseValue} instance.
  *
  * @param category  The category of this {@link DocumentPostResponseValue}
  */
  public void setCategory( @Nonnull final String category) {
    this.category = category;
  }

   /**
   * Set the status of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param status  The status of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status  The status of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link DocumentPostResponseValue} instance.
  *
  * @param status  The status of this {@link DocumentPostResponseValue}
  */
  public void setStatus( @Nonnull final String status) {
    this.status = status;
  }

   /**
   * Set the thumbnailStatus of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param thumbnailStatus  The thumbnailStatus of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue thumbnailStatus(@Nonnull final String thumbnailStatus) {
    this.thumbnailStatus = thumbnailStatus;
    return this;
  }

   /**
   * Get thumbnailStatus
   * @return thumbnailStatus  The thumbnailStatus of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getThumbnailStatus() {
    return thumbnailStatus;
  }

  /**
  * Set the thumbnailStatus of this {@link DocumentPostResponseValue} instance.
  *
  * @param thumbnailStatus  The thumbnailStatus of this {@link DocumentPostResponseValue}
  */
  public void setThumbnailStatus( @Nonnull final String thumbnailStatus) {
    this.thumbnailStatus = thumbnailStatus;
  }

   /**
   * Set the type of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param type  The type of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue type(@Nonnull final String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type  The type of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getType() {
    return type;
  }

  /**
  * Set the type of this {@link DocumentPostResponseValue} instance.
  *
  * @param type  The type of this {@link DocumentPostResponseValue}
  */
  public void setType( @Nonnull final String type) {
    this.type = type;
  }

   /**
   * Set the fileSize of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param fileSize  The fileSize of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue fileSize(@Nonnull final String fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Get fileSize
   * @return fileSize  The fileSize of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getFileSize() {
    return fileSize;
  }

  /**
  * Set the fileSize of this {@link DocumentPostResponseValue} instance.
  *
  * @param fileSize  The fileSize of this {@link DocumentPostResponseValue}
  */
  public void setFileSize( @Nonnull final String fileSize) {
    this.fileSize = fileSize;
  }

   /**
   * Set the uploadUrl of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param uploadUrl  The uploadUrl of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue uploadUrl(@Nonnull final String uploadUrl) {
    this.uploadUrl = uploadUrl;
    return this;
  }

   /**
   * Get uploadUrl
   * @return uploadUrl  The uploadUrl of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getUploadUrl() {
    return uploadUrl;
  }

  /**
  * Set the uploadUrl of this {@link DocumentPostResponseValue} instance.
  *
  * @param uploadUrl  The uploadUrl of this {@link DocumentPostResponseValue}
  */
  public void setUploadUrl( @Nonnull final String uploadUrl) {
    this.uploadUrl = uploadUrl;
  }

   /**
   * Set the adminData of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param adminData  The adminData of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue adminData(@Nonnull final DocumentPostResponseValueAdminData adminData) {
    this.adminData = adminData;
    return this;
  }

   /**
   * Get adminData
   * @return adminData  The adminData of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public DocumentPostResponseValueAdminData getAdminData() {
    return adminData;
  }

  /**
  * Set the adminData of this {@link DocumentPostResponseValue} instance.
  *
  * @param adminData  The adminData of this {@link DocumentPostResponseValue}
  */
  public void setAdminData( @Nonnull final DocumentPostResponseValueAdminData adminData) {
    this.adminData = adminData;
  }

   /**
   * Set the hostObjectId of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param hostObjectId  The hostObjectId of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue hostObjectId(@Nonnull final UUID hostObjectId) {
    this.hostObjectId = hostObjectId;
    return this;
  }

   /**
   * Get hostObjectId
   * @return hostObjectId  The hostObjectId of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public UUID getHostObjectId() {
    return hostObjectId;
  }

  /**
  * Set the hostObjectId of this {@link DocumentPostResponseValue} instance.
  *
  * @param hostObjectId  The hostObjectId of this {@link DocumentPostResponseValue}
  */
  public void setHostObjectId( @Nonnull final UUID hostObjectId) {
    this.hostObjectId = hostObjectId;
  }

   /**
   * Set the hostObjectType of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param hostObjectType  The hostObjectType of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue hostObjectType(@Nonnull final String hostObjectType) {
    this.hostObjectType = hostObjectType;
    return this;
  }

   /**
   * Get hostObjectType
   * @return hostObjectType  The hostObjectType of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getHostObjectType() {
    return hostObjectType;
  }

  /**
  * Set the hostObjectType of this {@link DocumentPostResponseValue} instance.
  *
  * @param hostObjectType  The hostObjectType of this {@link DocumentPostResponseValue}
  */
  public void setHostObjectType( @Nonnull final String hostObjectType) {
    this.hostObjectType = hostObjectType;
  }

   /**
   * Set the icon of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param icon  The icon of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue icon(@Nonnull final String icon) {
    this.icon = icon;
    return this;
  }

   /**
   * Get icon
   * @return icon  The icon of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getIcon() {
    return icon;
  }

  /**
  * Set the icon of this {@link DocumentPostResponseValue} instance.
  *
  * @param icon  The icon of this {@link DocumentPostResponseValue}
  */
  public void setIcon( @Nonnull final String icon) {
    this.icon = icon;
  }

   /**
   * Set the color of this {@link DocumentPostResponseValue} instance and return the same instance.
   *
   * @param color  The color of this {@link DocumentPostResponseValue}
   * @return The same instance of this {@link DocumentPostResponseValue} class
   */
   @Nonnull public DocumentPostResponseValue color(@Nonnull final String color) {
    this.color = color;
    return this;
  }

   /**
   * Get color
   * @return color  The color of this {@link DocumentPostResponseValue} instance.
  **/
  @Nonnull public String getColor() {
    return color;
  }

  /**
  * Set the color of this {@link DocumentPostResponseValue} instance.
  *
  * @param color  The color of this {@link DocumentPostResponseValue}
  */
  public void setColor( @Nonnull final String color) {
    this.color = color;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link DocumentPostResponseValue}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link DocumentPostResponseValue}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("DocumentPostResponseValue has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final DocumentPostResponseValue documentPostResponseValue = (DocumentPostResponseValue) o;
    return Objects.equals(this.cloudSdkCustomFields, documentPostResponseValue.cloudSdkCustomFields) &&
        Objects.equals(this.id, documentPostResponseValue.id) &&
        Objects.equals(this.title, documentPostResponseValue.title) &&
        Objects.equals(this.fileName, documentPostResponseValue.fileName) &&
        Objects.equals(this.category, documentPostResponseValue.category) &&
        Objects.equals(this.status, documentPostResponseValue.status) &&
        Objects.equals(this.thumbnailStatus, documentPostResponseValue.thumbnailStatus) &&
        Objects.equals(this.type, documentPostResponseValue.type) &&
        Objects.equals(this.fileSize, documentPostResponseValue.fileSize) &&
        Objects.equals(this.uploadUrl, documentPostResponseValue.uploadUrl) &&
        Objects.equals(this.adminData, documentPostResponseValue.adminData) &&
        Objects.equals(this.hostObjectId, documentPostResponseValue.hostObjectId) &&
        Objects.equals(this.hostObjectType, documentPostResponseValue.hostObjectType) &&
        Objects.equals(this.icon, documentPostResponseValue.icon) &&
        Objects.equals(this.color, documentPostResponseValue.color);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, title, fileName, category, status, thumbnailStatus, type, fileSize, uploadUrl, adminData, hostObjectId, hostObjectType, icon, color, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class DocumentPostResponseValue {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    thumbnailStatus: ").append(toIndentedString(thumbnailStatus)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    uploadUrl: ").append(toIndentedString(uploadUrl)).append("\n");
    sb.append("    adminData: ").append(toIndentedString(adminData)).append("\n");
    sb.append("    hostObjectId: ").append(toIndentedString(hostObjectId)).append("\n");
    sb.append("    hostObjectType: ").append(toIndentedString(hostObjectType)).append("\n");
    sb.append("    icon: ").append(toIndentedString(icon)).append("\n");
    sb.append("    color: ").append(toIndentedString(color)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

