

/*
 * Case Service
 * Cases are records of service or support requests from an account or individual customer used to track interactions with the requestor. Cases also record details like how much time has passed since the case was created, what actions were taken to resolve the issue, priority or associated products, and much more.  Use this API to view, create, and manage your cases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CaseQueryResponseValueInnerTimePoints
 */

// CHECKSTYLE:OFF
public class CaseQueryResponseValueInnerTimePoints 
// CHECKSTYLE:ON
{
  @JsonProperty("reportedOn")
  private OffsetDateTime reportedOn;

  @JsonProperty("escalatedOn")
  private OffsetDateTime escalatedOn;

  @JsonProperty("completedOn")
  private OffsetDateTime completedOn;

  @JsonProperty("completionDueOn")
  private OffsetDateTime completionDueOn;

  @JsonProperty("assignedToCustomerOn")
  private OffsetDateTime assignedToCustomerOn;

  @JsonProperty("assignedToProcessorOn")
  private OffsetDateTime assignedToProcessorOn;

  @JsonProperty("initialReviewDueOn")
  private OffsetDateTime initialReviewDueOn;

  @JsonProperty("initialReviewCompletedOn")
  private OffsetDateTime initialReviewCompletedOn;

  @JsonProperty("resolutionDueOn")
  private OffsetDateTime resolutionDueOn;

  @JsonProperty("responseDueOn")
  private OffsetDateTime responseDueOn;

  @JsonProperty("closedOn")
  private OffsetDateTime closedOn;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the reportedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param reportedOn  The reportedOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints reportedOn(@Nonnull final OffsetDateTime reportedOn) {
    this.reportedOn = reportedOn;
    return this;
  }

   /**
   * Get reportedOn
   * @return reportedOn  The reportedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getReportedOn() {
    return reportedOn;
  }

  /**
  * Set the reportedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param reportedOn  The reportedOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setReportedOn( @Nonnull final OffsetDateTime reportedOn) {
    this.reportedOn = reportedOn;
  }

   /**
   * Set the escalatedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param escalatedOn  The escalatedOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints escalatedOn(@Nonnull final OffsetDateTime escalatedOn) {
    this.escalatedOn = escalatedOn;
    return this;
  }

   /**
   * Get escalatedOn
   * @return escalatedOn  The escalatedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getEscalatedOn() {
    return escalatedOn;
  }

  /**
  * Set the escalatedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param escalatedOn  The escalatedOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setEscalatedOn( @Nonnull final OffsetDateTime escalatedOn) {
    this.escalatedOn = escalatedOn;
  }

   /**
   * Set the completedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param completedOn  The completedOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints completedOn(@Nonnull final OffsetDateTime completedOn) {
    this.completedOn = completedOn;
    return this;
  }

   /**
   * Get completedOn
   * @return completedOn  The completedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getCompletedOn() {
    return completedOn;
  }

  /**
  * Set the completedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param completedOn  The completedOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setCompletedOn( @Nonnull final OffsetDateTime completedOn) {
    this.completedOn = completedOn;
  }

   /**
   * Set the completionDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param completionDueOn  The completionDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints completionDueOn(@Nonnull final OffsetDateTime completionDueOn) {
    this.completionDueOn = completionDueOn;
    return this;
  }

   /**
   * Get completionDueOn
   * @return completionDueOn  The completionDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getCompletionDueOn() {
    return completionDueOn;
  }

  /**
  * Set the completionDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param completionDueOn  The completionDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setCompletionDueOn( @Nonnull final OffsetDateTime completionDueOn) {
    this.completionDueOn = completionDueOn;
  }

   /**
   * Set the assignedToCustomerOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param assignedToCustomerOn  The assignedToCustomerOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints assignedToCustomerOn(@Nonnull final OffsetDateTime assignedToCustomerOn) {
    this.assignedToCustomerOn = assignedToCustomerOn;
    return this;
  }

   /**
   * Get assignedToCustomerOn
   * @return assignedToCustomerOn  The assignedToCustomerOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getAssignedToCustomerOn() {
    return assignedToCustomerOn;
  }

  /**
  * Set the assignedToCustomerOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param assignedToCustomerOn  The assignedToCustomerOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setAssignedToCustomerOn( @Nonnull final OffsetDateTime assignedToCustomerOn) {
    this.assignedToCustomerOn = assignedToCustomerOn;
  }

   /**
   * Set the assignedToProcessorOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param assignedToProcessorOn  The assignedToProcessorOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints assignedToProcessorOn(@Nonnull final OffsetDateTime assignedToProcessorOn) {
    this.assignedToProcessorOn = assignedToProcessorOn;
    return this;
  }

   /**
   * Get assignedToProcessorOn
   * @return assignedToProcessorOn  The assignedToProcessorOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getAssignedToProcessorOn() {
    return assignedToProcessorOn;
  }

  /**
  * Set the assignedToProcessorOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param assignedToProcessorOn  The assignedToProcessorOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setAssignedToProcessorOn( @Nonnull final OffsetDateTime assignedToProcessorOn) {
    this.assignedToProcessorOn = assignedToProcessorOn;
  }

   /**
   * Set the initialReviewDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param initialReviewDueOn  The initialReviewDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints initialReviewDueOn(@Nonnull final OffsetDateTime initialReviewDueOn) {
    this.initialReviewDueOn = initialReviewDueOn;
    return this;
  }

   /**
   * Get initialReviewDueOn
   * @return initialReviewDueOn  The initialReviewDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getInitialReviewDueOn() {
    return initialReviewDueOn;
  }

  /**
  * Set the initialReviewDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param initialReviewDueOn  The initialReviewDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setInitialReviewDueOn( @Nonnull final OffsetDateTime initialReviewDueOn) {
    this.initialReviewDueOn = initialReviewDueOn;
  }

   /**
   * Set the initialReviewCompletedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param initialReviewCompletedOn  The initialReviewCompletedOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints initialReviewCompletedOn(@Nonnull final OffsetDateTime initialReviewCompletedOn) {
    this.initialReviewCompletedOn = initialReviewCompletedOn;
    return this;
  }

   /**
   * Get initialReviewCompletedOn
   * @return initialReviewCompletedOn  The initialReviewCompletedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getInitialReviewCompletedOn() {
    return initialReviewCompletedOn;
  }

  /**
  * Set the initialReviewCompletedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param initialReviewCompletedOn  The initialReviewCompletedOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setInitialReviewCompletedOn( @Nonnull final OffsetDateTime initialReviewCompletedOn) {
    this.initialReviewCompletedOn = initialReviewCompletedOn;
  }

   /**
   * Set the resolutionDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param resolutionDueOn  The resolutionDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints resolutionDueOn(@Nonnull final OffsetDateTime resolutionDueOn) {
    this.resolutionDueOn = resolutionDueOn;
    return this;
  }

   /**
   * Get resolutionDueOn
   * @return resolutionDueOn  The resolutionDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getResolutionDueOn() {
    return resolutionDueOn;
  }

  /**
  * Set the resolutionDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param resolutionDueOn  The resolutionDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setResolutionDueOn( @Nonnull final OffsetDateTime resolutionDueOn) {
    this.resolutionDueOn = resolutionDueOn;
  }

   /**
   * Set the responseDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param responseDueOn  The responseDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints responseDueOn(@Nonnull final OffsetDateTime responseDueOn) {
    this.responseDueOn = responseDueOn;
    return this;
  }

   /**
   * Get responseDueOn
   * @return responseDueOn  The responseDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getResponseDueOn() {
    return responseDueOn;
  }

  /**
  * Set the responseDueOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param responseDueOn  The responseDueOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setResponseDueOn( @Nonnull final OffsetDateTime responseDueOn) {
    this.responseDueOn = responseDueOn;
  }

   /**
   * Set the closedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance and return the same instance.
   *
   * @param closedOn  The closedOn of this {@link CaseQueryResponseValueInnerTimePoints}
   * @return The same instance of this {@link CaseQueryResponseValueInnerTimePoints} class
   */
   @Nonnull public CaseQueryResponseValueInnerTimePoints closedOn(@Nonnull final OffsetDateTime closedOn) {
    this.closedOn = closedOn;
    return this;
  }

   /**
   * Get closedOn
   * @return closedOn  The closedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  **/
  @Nonnull public OffsetDateTime getClosedOn() {
    return closedOn;
  }

  /**
  * Set the closedOn of this {@link CaseQueryResponseValueInnerTimePoints} instance.
  *
  * @param closedOn  The closedOn of this {@link CaseQueryResponseValueInnerTimePoints}
  */
  public void setClosedOn( @Nonnull final OffsetDateTime closedOn) {
    this.closedOn = closedOn;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CaseQueryResponseValueInnerTimePoints}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CaseQueryResponseValueInnerTimePoints}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CaseQueryResponseValueInnerTimePoints has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CaseQueryResponseValueInnerTimePoints caseQueryResponseValueInnerTimePoints = (CaseQueryResponseValueInnerTimePoints) o;
    return Objects.equals(this.cloudSdkCustomFields, caseQueryResponseValueInnerTimePoints.cloudSdkCustomFields) &&
        Objects.equals(this.reportedOn, caseQueryResponseValueInnerTimePoints.reportedOn) &&
        Objects.equals(this.escalatedOn, caseQueryResponseValueInnerTimePoints.escalatedOn) &&
        Objects.equals(this.completedOn, caseQueryResponseValueInnerTimePoints.completedOn) &&
        Objects.equals(this.completionDueOn, caseQueryResponseValueInnerTimePoints.completionDueOn) &&
        Objects.equals(this.assignedToCustomerOn, caseQueryResponseValueInnerTimePoints.assignedToCustomerOn) &&
        Objects.equals(this.assignedToProcessorOn, caseQueryResponseValueInnerTimePoints.assignedToProcessorOn) &&
        Objects.equals(this.initialReviewDueOn, caseQueryResponseValueInnerTimePoints.initialReviewDueOn) &&
        Objects.equals(this.initialReviewCompletedOn, caseQueryResponseValueInnerTimePoints.initialReviewCompletedOn) &&
        Objects.equals(this.resolutionDueOn, caseQueryResponseValueInnerTimePoints.resolutionDueOn) &&
        Objects.equals(this.responseDueOn, caseQueryResponseValueInnerTimePoints.responseDueOn) &&
        Objects.equals(this.closedOn, caseQueryResponseValueInnerTimePoints.closedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportedOn, escalatedOn, completedOn, completionDueOn, assignedToCustomerOn, assignedToProcessorOn, initialReviewDueOn, initialReviewCompletedOn, resolutionDueOn, responseDueOn, closedOn, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CaseQueryResponseValueInnerTimePoints {\n");
    sb.append("    reportedOn: ").append(toIndentedString(reportedOn)).append("\n");
    sb.append("    escalatedOn: ").append(toIndentedString(escalatedOn)).append("\n");
    sb.append("    completedOn: ").append(toIndentedString(completedOn)).append("\n");
    sb.append("    completionDueOn: ").append(toIndentedString(completionDueOn)).append("\n");
    sb.append("    assignedToCustomerOn: ").append(toIndentedString(assignedToCustomerOn)).append("\n");
    sb.append("    assignedToProcessorOn: ").append(toIndentedString(assignedToProcessorOn)).append("\n");
    sb.append("    initialReviewDueOn: ").append(toIndentedString(initialReviewDueOn)).append("\n");
    sb.append("    initialReviewCompletedOn: ").append(toIndentedString(initialReviewCompletedOn)).append("\n");
    sb.append("    resolutionDueOn: ").append(toIndentedString(resolutionDueOn)).append("\n");
    sb.append("    responseDueOn: ").append(toIndentedString(responseDueOn)).append("\n");
    sb.append("    closedOn: ").append(toIndentedString(closedOn)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

