

/*
 * Case Service
 * Cases are records of service or support requests from an account or individual customer used to track interactions with the requestor. Cases also record details like how much time has passed since the case was created, what actions were taken to resolve the issue, priority or associated products, and much more.  Use this API to view, create, and manage your cases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CaseReadResponseValueDurationTerms
 */

// CHECKSTYLE:OFF
public class CaseReadResponseValueDurationTerms 
// CHECKSTYLE:ON
{
  @JsonProperty("durationWithAgent")
  private String durationWithAgent;

  @JsonProperty("durationWithCustomer")
  private String durationWithCustomer;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the durationWithAgent of this {@link CaseReadResponseValueDurationTerms} instance and return the same instance.
   *
   * @param durationWithAgent  The durationWithAgent of this {@link CaseReadResponseValueDurationTerms}
   * @return The same instance of this {@link CaseReadResponseValueDurationTerms} class
   */
   @Nonnull public CaseReadResponseValueDurationTerms durationWithAgent(@Nonnull final String durationWithAgent) {
    this.durationWithAgent = durationWithAgent;
    return this;
  }

   /**
   * Get durationWithAgent
   * @return durationWithAgent  The durationWithAgent of this {@link CaseReadResponseValueDurationTerms} instance.
  **/
  @Nonnull public String getDurationWithAgent() {
    return durationWithAgent;
  }

  /**
  * Set the durationWithAgent of this {@link CaseReadResponseValueDurationTerms} instance.
  *
  * @param durationWithAgent  The durationWithAgent of this {@link CaseReadResponseValueDurationTerms}
  */
  public void setDurationWithAgent( @Nonnull final String durationWithAgent) {
    this.durationWithAgent = durationWithAgent;
  }

   /**
   * Set the durationWithCustomer of this {@link CaseReadResponseValueDurationTerms} instance and return the same instance.
   *
   * @param durationWithCustomer  The durationWithCustomer of this {@link CaseReadResponseValueDurationTerms}
   * @return The same instance of this {@link CaseReadResponseValueDurationTerms} class
   */
   @Nonnull public CaseReadResponseValueDurationTerms durationWithCustomer(@Nonnull final String durationWithCustomer) {
    this.durationWithCustomer = durationWithCustomer;
    return this;
  }

   /**
   * Get durationWithCustomer
   * @return durationWithCustomer  The durationWithCustomer of this {@link CaseReadResponseValueDurationTerms} instance.
  **/
  @Nonnull public String getDurationWithCustomer() {
    return durationWithCustomer;
  }

  /**
  * Set the durationWithCustomer of this {@link CaseReadResponseValueDurationTerms} instance.
  *
  * @param durationWithCustomer  The durationWithCustomer of this {@link CaseReadResponseValueDurationTerms}
  */
  public void setDurationWithCustomer( @Nonnull final String durationWithCustomer) {
    this.durationWithCustomer = durationWithCustomer;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CaseReadResponseValueDurationTerms}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CaseReadResponseValueDurationTerms}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CaseReadResponseValueDurationTerms has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CaseReadResponseValueDurationTerms caseReadResponseValueDurationTerms = (CaseReadResponseValueDurationTerms) o;
    return Objects.equals(this.cloudSdkCustomFields, caseReadResponseValueDurationTerms.cloudSdkCustomFields) &&
        Objects.equals(this.durationWithAgent, caseReadResponseValueDurationTerms.durationWithAgent) &&
        Objects.equals(this.durationWithCustomer, caseReadResponseValueDurationTerms.durationWithCustomer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(durationWithAgent, durationWithCustomer, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CaseReadResponseValueDurationTerms {\n");
    sb.append("    durationWithAgent: ").append(toIndentedString(durationWithAgent)).append("\n");
    sb.append("    durationWithCustomer: ").append(toIndentedString(durationWithCustomer)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

