

/*
 * Registered Product Service
 * The registered product is an instance of a product associated with a customer and generally has a serial ID. Registered product contains information describing its physical location, parties involved, such as the customer or employee responsible, product, and warranty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.time.OffsetDateTime;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * RegisteredProductqueryresponseValueInnerWarranty
 */

// CHECKSTYLE:OFF
public class RegisteredProductqueryresponseValueInnerWarranty 
// CHECKSTYLE:ON
{
  @JsonProperty("displayId")
  private String displayId;

  @JsonProperty("name")
  private String name;

  @JsonProperty("id")
  private UUID id;

  @JsonProperty("endDate")
  private OffsetDateTime endDate;

  @JsonProperty("startDate")
  private OffsetDateTime startDate;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the displayId of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance and return the same instance.
   *
   * @param displayId  The displayId of this {@link RegisteredProductqueryresponseValueInnerWarranty}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerWarranty} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerWarranty displayId(@Nonnull final String displayId) {
    this.displayId = displayId;
    return this;
  }

   /**
   * Get displayId
   * @return displayId  The displayId of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  **/
  @Nonnull public String getDisplayId() {
    return displayId;
  }

  /**
  * Set the displayId of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  *
  * @param displayId  The displayId of this {@link RegisteredProductqueryresponseValueInnerWarranty}
  */
  public void setDisplayId( @Nonnull final String displayId) {
    this.displayId = displayId;
  }

   /**
   * Set the name of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance and return the same instance.
   *
   * @param name  The name of this {@link RegisteredProductqueryresponseValueInnerWarranty}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerWarranty} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerWarranty name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name  The name of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  *
  * @param name  The name of this {@link RegisteredProductqueryresponseValueInnerWarranty}
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

   /**
   * Set the id of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance and return the same instance.
   *
   * @param id  The id of this {@link RegisteredProductqueryresponseValueInnerWarranty}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerWarranty} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerWarranty id(@Nonnull final UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id  The id of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  **/
  @Nonnull public UUID getId() {
    return id;
  }

  /**
  * Set the id of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  *
  * @param id  The id of this {@link RegisteredProductqueryresponseValueInnerWarranty}
  */
  public void setId( @Nonnull final UUID id) {
    this.id = id;
  }

   /**
   * Set the endDate of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance and return the same instance.
   *
   * @param endDate  The endDate of this {@link RegisteredProductqueryresponseValueInnerWarranty}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerWarranty} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerWarranty endDate(@Nonnull final OffsetDateTime endDate) {
    this.endDate = endDate;
    return this;
  }

   /**
   * Get endDate
   * @return endDate  The endDate of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  **/
  @Nonnull public OffsetDateTime getEndDate() {
    return endDate;
  }

  /**
  * Set the endDate of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  *
  * @param endDate  The endDate of this {@link RegisteredProductqueryresponseValueInnerWarranty}
  */
  public void setEndDate( @Nonnull final OffsetDateTime endDate) {
    this.endDate = endDate;
  }

   /**
   * Set the startDate of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance and return the same instance.
   *
   * @param startDate  The startDate of this {@link RegisteredProductqueryresponseValueInnerWarranty}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerWarranty} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerWarranty startDate(@Nonnull final OffsetDateTime startDate) {
    this.startDate = startDate;
    return this;
  }

   /**
   * Get startDate
   * @return startDate  The startDate of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  **/
  @Nonnull public OffsetDateTime getStartDate() {
    return startDate;
  }

  /**
  * Set the startDate of this {@link RegisteredProductqueryresponseValueInnerWarranty} instance.
  *
  * @param startDate  The startDate of this {@link RegisteredProductqueryresponseValueInnerWarranty}
  */
  public void setStartDate( @Nonnull final OffsetDateTime startDate) {
    this.startDate = startDate;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link RegisteredProductqueryresponseValueInnerWarranty}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link RegisteredProductqueryresponseValueInnerWarranty}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("RegisteredProductqueryresponseValueInnerWarranty has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final RegisteredProductqueryresponseValueInnerWarranty registeredProductqueryresponseValueInnerWarranty = (RegisteredProductqueryresponseValueInnerWarranty) o;
    return Objects.equals(this.cloudSdkCustomFields, registeredProductqueryresponseValueInnerWarranty.cloudSdkCustomFields) &&
        Objects.equals(this.displayId, registeredProductqueryresponseValueInnerWarranty.displayId) &&
        Objects.equals(this.name, registeredProductqueryresponseValueInnerWarranty.name) &&
        Objects.equals(this.id, registeredProductqueryresponseValueInnerWarranty.id) &&
        Objects.equals(this.endDate, registeredProductqueryresponseValueInnerWarranty.endDate) &&
        Objects.equals(this.startDate, registeredProductqueryresponseValueInnerWarranty.startDate);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayId, name, id, endDate, startDate, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredProductqueryresponseValueInnerWarranty {\n");
    sb.append("    displayId: ").append(toIndentedString(displayId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    endDate: ").append(toIndentedString(endDate)).append("\n");
    sb.append("    startDate: ").append(toIndentedString(startDate)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

