

/*
 * Case Service
 * Cases are records of service or support requests from an account or individual customer used to track interactions with the requestor. Cases also record details like how much time has passed since the case was created, what actions were taken to resolve the issue, priority or associated products, and much more.  Use this API to view, create, and manage your cases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CaseQueryResponseValueInnerDescription
 */

// CHECKSTYLE:OFF
public class CaseQueryResponseValueInnerDescription 
// CHECKSTYLE:ON
{
  @JsonProperty("noteId")
  private UUID noteId;

  @JsonProperty("content")
  private String content;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the noteId of this {@link CaseQueryResponseValueInnerDescription} instance and return the same instance.
   *
   * @param noteId  The noteId of this {@link CaseQueryResponseValueInnerDescription}
   * @return The same instance of this {@link CaseQueryResponseValueInnerDescription} class
   */
   @Nonnull public CaseQueryResponseValueInnerDescription noteId(@Nonnull final UUID noteId) {
    this.noteId = noteId;
    return this;
  }

   /**
   * Get noteId
   * @return noteId  The noteId of this {@link CaseQueryResponseValueInnerDescription} instance.
  **/
  @Nonnull public UUID getNoteId() {
    return noteId;
  }

  /**
  * Set the noteId of this {@link CaseQueryResponseValueInnerDescription} instance.
  *
  * @param noteId  The noteId of this {@link CaseQueryResponseValueInnerDescription}
  */
  public void setNoteId( @Nonnull final UUID noteId) {
    this.noteId = noteId;
  }

   /**
   * Set the content of this {@link CaseQueryResponseValueInnerDescription} instance and return the same instance.
   *
   * @param content  The content of this {@link CaseQueryResponseValueInnerDescription}
   * @return The same instance of this {@link CaseQueryResponseValueInnerDescription} class
   */
   @Nonnull public CaseQueryResponseValueInnerDescription content(@Nonnull final String content) {
    this.content = content;
    return this;
  }

   /**
   * Get content
   * @return content  The content of this {@link CaseQueryResponseValueInnerDescription} instance.
  **/
  @Nonnull public String getContent() {
    return content;
  }

  /**
  * Set the content of this {@link CaseQueryResponseValueInnerDescription} instance.
  *
  * @param content  The content of this {@link CaseQueryResponseValueInnerDescription}
  */
  public void setContent( @Nonnull final String content) {
    this.content = content;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CaseQueryResponseValueInnerDescription}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CaseQueryResponseValueInnerDescription}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CaseQueryResponseValueInnerDescription has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CaseQueryResponseValueInnerDescription caseQueryResponseValueInnerDescription = (CaseQueryResponseValueInnerDescription) o;
    return Objects.equals(this.cloudSdkCustomFields, caseQueryResponseValueInnerDescription.cloudSdkCustomFields) &&
        Objects.equals(this.noteId, caseQueryResponseValueInnerDescription.noteId) &&
        Objects.equals(this.content, caseQueryResponseValueInnerDescription.content);
  }

  @Override
  public int hashCode() {
    return Objects.hash(noteId, content, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CaseQueryResponseValueInnerDescription {\n");
    sb.append("    noteId: ").append(toIndentedString(noteId)).append("\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

