

/*
 * Case Service
 * Cases are records of service or support requests from an account or individual customer used to track interactions with the requestor. Cases also record details like how much time has passed since the case was created, what actions were taken to resolve the issue, priority or associated products, and much more.  Use this API to view, create, and manage your cases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerAccount;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerContact;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerDescription;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerFunctionalLocationsInner;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerIndividualCustomer;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerNotesInner;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerRegisteredProductsInner;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerRelatedObjectsInner;
import com.sap.cnsmodules.model.CaseQueryResponseValueInnerServiceTeam;
import com.sap.cnsmodules.model.CaseReadResponseValueAdminData;
import com.sap.cnsmodules.model.CaseReadResponseValueDurationTerms;
import com.sap.cnsmodules.model.CaseReadResponseValueTimePoints;
import java.util.ArrayList;
import java.util.List;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CaseReadResponseValue
 */

// CHECKSTYLE:OFF
public class CaseReadResponseValue 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private UUID id;

  @JsonProperty("displayId")
  private String displayId;

  @JsonProperty("subject")
  private String subject;

  @JsonProperty("priority")
  private String priority;

  @JsonProperty("priorityDescription")
  private String priorityDescription;

  @JsonProperty("origin")
  private String origin;

  @JsonProperty("caseType")
  private String caseType;

  @JsonProperty("caseTypeDescription")
  private String caseTypeDescription;

  @JsonProperty("status")
  private String status;

  @JsonProperty("statusDescription")
  private String statusDescription;

  @JsonProperty("escalationStatus")
  private String escalationStatus;

  @JsonProperty("registeredProducts")
  private List<CaseQueryResponseValueInnerRegisteredProductsInner> registeredProducts = new ArrayList<>();

  @JsonProperty("functionalLocations")
  private List<CaseQueryResponseValueInnerFunctionalLocationsInner> functionalLocations = new ArrayList<>();

  @JsonProperty("productInstallPoints")
  private List<CaseQueryResponseValueInnerFunctionalLocationsInner> productInstallPoints = new ArrayList<>();

  @JsonProperty("installedBases")
  private List<CaseQueryResponseValueInnerFunctionalLocationsInner> installedBases = new ArrayList<>();

  @JsonProperty("account")
  private CaseQueryResponseValueInnerAccount account;

  @JsonProperty("contact")
  private CaseQueryResponseValueInnerContact contact;

  @JsonProperty("individualCustomer")
  private CaseQueryResponseValueInnerIndividualCustomer individualCustomer;

  @JsonProperty("processor")
  private CaseQueryResponseValueInnerIndividualCustomer processor;

  @JsonProperty("approvers")
  private List<CaseQueryResponseValueInnerIndividualCustomer> approvers = new ArrayList<>();

  @JsonProperty("serviceTeam")
  private CaseQueryResponseValueInnerServiceTeam serviceTeam;

  @JsonProperty("description")
  private CaseQueryResponseValueInnerDescription description;

  @JsonProperty("notes")
  private List<CaseQueryResponseValueInnerNotesInner> notes = new ArrayList<>();

  @JsonProperty("relatedObjects")
  private List<CaseQueryResponseValueInnerRelatedObjectsInner> relatedObjects = new ArrayList<>();

  @JsonProperty("timePoints")
  private CaseReadResponseValueTimePoints timePoints;

  @JsonProperty("categoryLevel1")
  private CaseQueryResponseValueInnerFunctionalLocationsInner categoryLevel1;

  @JsonProperty("categoryLevel2")
  private CaseQueryResponseValueInnerFunctionalLocationsInner categoryLevel2;

  @JsonProperty("serviceLevelId")
  private UUID serviceLevelId;

  @JsonProperty("durationTerms")
  private CaseReadResponseValueDurationTerms durationTerms;

  @JsonProperty("isRead")
  private Boolean isRead;

  @JsonProperty("isEndOfPurpose")
  private Boolean isEndOfPurpose;

  @JsonProperty("isDepersonalized")
  private Boolean isDepersonalized;

  @JsonProperty("adminData")
  private CaseReadResponseValueAdminData adminData;

  @JsonProperty("extensions")
  private Object extensions;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param id  The id of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue id(@Nonnull final UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id  The id of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public UUID getId() {
    return id;
  }

  /**
  * Set the id of this {@link CaseReadResponseValue} instance.
  *
  * @param id  The id of this {@link CaseReadResponseValue}
  */
  public void setId( @Nonnull final UUID id) {
    this.id = id;
  }

   /**
   * Set the displayId of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param displayId  The displayId of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue displayId(@Nonnull final String displayId) {
    this.displayId = displayId;
    return this;
  }

   /**
   * Get displayId
   * @return displayId  The displayId of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getDisplayId() {
    return displayId;
  }

  /**
  * Set the displayId of this {@link CaseReadResponseValue} instance.
  *
  * @param displayId  The displayId of this {@link CaseReadResponseValue}
  */
  public void setDisplayId( @Nonnull final String displayId) {
    this.displayId = displayId;
  }

   /**
   * Set the subject of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param subject  The subject of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue subject(@Nonnull final String subject) {
    this.subject = subject;
    return this;
  }

   /**
   * Get subject
   * @return subject  The subject of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getSubject() {
    return subject;
  }

  /**
  * Set the subject of this {@link CaseReadResponseValue} instance.
  *
  * @param subject  The subject of this {@link CaseReadResponseValue}
  */
  public void setSubject( @Nonnull final String subject) {
    this.subject = subject;
  }

   /**
   * Set the priority of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param priority  The priority of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue priority(@Nonnull final String priority) {
    this.priority = priority;
    return this;
  }

   /**
   * Get priority
   * @return priority  The priority of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getPriority() {
    return priority;
  }

  /**
  * Set the priority of this {@link CaseReadResponseValue} instance.
  *
  * @param priority  The priority of this {@link CaseReadResponseValue}
  */
  public void setPriority( @Nonnull final String priority) {
    this.priority = priority;
  }

   /**
   * Set the priorityDescription of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param priorityDescription  The priorityDescription of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue priorityDescription(@Nonnull final String priorityDescription) {
    this.priorityDescription = priorityDescription;
    return this;
  }

   /**
   * Get priorityDescription
   * @return priorityDescription  The priorityDescription of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getPriorityDescription() {
    return priorityDescription;
  }

  /**
  * Set the priorityDescription of this {@link CaseReadResponseValue} instance.
  *
  * @param priorityDescription  The priorityDescription of this {@link CaseReadResponseValue}
  */
  public void setPriorityDescription( @Nonnull final String priorityDescription) {
    this.priorityDescription = priorityDescription;
  }

   /**
   * Set the origin of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param origin  The origin of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue origin(@Nonnull final String origin) {
    this.origin = origin;
    return this;
  }

   /**
   * Get origin
   * @return origin  The origin of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getOrigin() {
    return origin;
  }

  /**
  * Set the origin of this {@link CaseReadResponseValue} instance.
  *
  * @param origin  The origin of this {@link CaseReadResponseValue}
  */
  public void setOrigin( @Nonnull final String origin) {
    this.origin = origin;
  }

   /**
   * Set the caseType of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param caseType  The caseType of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue caseType(@Nonnull final String caseType) {
    this.caseType = caseType;
    return this;
  }

   /**
   * Get caseType
   * @return caseType  The caseType of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getCaseType() {
    return caseType;
  }

  /**
  * Set the caseType of this {@link CaseReadResponseValue} instance.
  *
  * @param caseType  The caseType of this {@link CaseReadResponseValue}
  */
  public void setCaseType( @Nonnull final String caseType) {
    this.caseType = caseType;
  }

   /**
   * Set the caseTypeDescription of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param caseTypeDescription  The caseTypeDescription of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue caseTypeDescription(@Nonnull final String caseTypeDescription) {
    this.caseTypeDescription = caseTypeDescription;
    return this;
  }

   /**
   * Get caseTypeDescription
   * @return caseTypeDescription  The caseTypeDescription of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getCaseTypeDescription() {
    return caseTypeDescription;
  }

  /**
  * Set the caseTypeDescription of this {@link CaseReadResponseValue} instance.
  *
  * @param caseTypeDescription  The caseTypeDescription of this {@link CaseReadResponseValue}
  */
  public void setCaseTypeDescription( @Nonnull final String caseTypeDescription) {
    this.caseTypeDescription = caseTypeDescription;
  }

   /**
   * Set the status of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param status  The status of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status  The status of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link CaseReadResponseValue} instance.
  *
  * @param status  The status of this {@link CaseReadResponseValue}
  */
  public void setStatus( @Nonnull final String status) {
    this.status = status;
  }

   /**
   * Set the statusDescription of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param statusDescription  The statusDescription of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue statusDescription(@Nonnull final String statusDescription) {
    this.statusDescription = statusDescription;
    return this;
  }

   /**
   * Get statusDescription
   * @return statusDescription  The statusDescription of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getStatusDescription() {
    return statusDescription;
  }

  /**
  * Set the statusDescription of this {@link CaseReadResponseValue} instance.
  *
  * @param statusDescription  The statusDescription of this {@link CaseReadResponseValue}
  */
  public void setStatusDescription( @Nonnull final String statusDescription) {
    this.statusDescription = statusDescription;
  }

   /**
   * Set the escalationStatus of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param escalationStatus  The escalationStatus of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue escalationStatus(@Nonnull final String escalationStatus) {
    this.escalationStatus = escalationStatus;
    return this;
  }

   /**
   * Get escalationStatus
   * @return escalationStatus  The escalationStatus of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public String getEscalationStatus() {
    return escalationStatus;
  }

  /**
  * Set the escalationStatus of this {@link CaseReadResponseValue} instance.
  *
  * @param escalationStatus  The escalationStatus of this {@link CaseReadResponseValue}
  */
  public void setEscalationStatus( @Nonnull final String escalationStatus) {
    this.escalationStatus = escalationStatus;
  }

   /**
   * Set the registeredProducts of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param registeredProducts  The registeredProducts of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue registeredProducts(@Nonnull final List<CaseQueryResponseValueInnerRegisteredProductsInner> registeredProducts) {
    this.registeredProducts = registeredProducts;
    return this;
  }
  /**
  * Add one RegisteredProducts instance to this {@link CaseReadResponseValue}.
  * @param registeredProductsItem The RegisteredProducts that should be added
  * @return The same instance of type {@link CaseReadResponseValue}
  */
  @Nonnull public CaseReadResponseValue addRegisteredProductsItem( @Nonnull final CaseQueryResponseValueInnerRegisteredProductsInner registeredProductsItem) {
    if (this.registeredProducts == null) {
      this.registeredProducts = new ArrayList<>();
    }
    this.registeredProducts.add(registeredProductsItem);
    return this;
  }

   /**
   * Get registeredProducts
   * @return registeredProducts  The registeredProducts of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInnerRegisteredProductsInner> getRegisteredProducts() {
    return registeredProducts;
  }

  /**
  * Set the registeredProducts of this {@link CaseReadResponseValue} instance.
  *
  * @param registeredProducts  The registeredProducts of this {@link CaseReadResponseValue}
  */
  public void setRegisteredProducts( @Nonnull final List<CaseQueryResponseValueInnerRegisteredProductsInner> registeredProducts) {
    this.registeredProducts = registeredProducts;
  }

   /**
   * Set the functionalLocations of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param functionalLocations  The functionalLocations of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue functionalLocations(@Nonnull final List<CaseQueryResponseValueInnerFunctionalLocationsInner> functionalLocations) {
    this.functionalLocations = functionalLocations;
    return this;
  }
  /**
  * Add one FunctionalLocations instance to this {@link CaseReadResponseValue}.
  * @param functionalLocationsItem The FunctionalLocations that should be added
  * @return The same instance of type {@link CaseReadResponseValue}
  */
  @Nonnull public CaseReadResponseValue addFunctionalLocationsItem( @Nonnull final CaseQueryResponseValueInnerFunctionalLocationsInner functionalLocationsItem) {
    if (this.functionalLocations == null) {
      this.functionalLocations = new ArrayList<>();
    }
    this.functionalLocations.add(functionalLocationsItem);
    return this;
  }

   /**
   * Get functionalLocations
   * @return functionalLocations  The functionalLocations of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInnerFunctionalLocationsInner> getFunctionalLocations() {
    return functionalLocations;
  }

  /**
  * Set the functionalLocations of this {@link CaseReadResponseValue} instance.
  *
  * @param functionalLocations  The functionalLocations of this {@link CaseReadResponseValue}
  */
  public void setFunctionalLocations( @Nonnull final List<CaseQueryResponseValueInnerFunctionalLocationsInner> functionalLocations) {
    this.functionalLocations = functionalLocations;
  }

   /**
   * Set the productInstallPoints of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param productInstallPoints  The productInstallPoints of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue productInstallPoints(@Nonnull final List<CaseQueryResponseValueInnerFunctionalLocationsInner> productInstallPoints) {
    this.productInstallPoints = productInstallPoints;
    return this;
  }
  /**
  * Add one ProductInstallPoints instance to this {@link CaseReadResponseValue}.
  * @param productInstallPointsItem The ProductInstallPoints that should be added
  * @return The same instance of type {@link CaseReadResponseValue}
  */
  @Nonnull public CaseReadResponseValue addProductInstallPointsItem( @Nonnull final CaseQueryResponseValueInnerFunctionalLocationsInner productInstallPointsItem) {
    if (this.productInstallPoints == null) {
      this.productInstallPoints = new ArrayList<>();
    }
    this.productInstallPoints.add(productInstallPointsItem);
    return this;
  }

   /**
   * Get productInstallPoints
   * @return productInstallPoints  The productInstallPoints of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInnerFunctionalLocationsInner> getProductInstallPoints() {
    return productInstallPoints;
  }

  /**
  * Set the productInstallPoints of this {@link CaseReadResponseValue} instance.
  *
  * @param productInstallPoints  The productInstallPoints of this {@link CaseReadResponseValue}
  */
  public void setProductInstallPoints( @Nonnull final List<CaseQueryResponseValueInnerFunctionalLocationsInner> productInstallPoints) {
    this.productInstallPoints = productInstallPoints;
  }

   /**
   * Set the installedBases of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param installedBases  The installedBases of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue installedBases(@Nonnull final List<CaseQueryResponseValueInnerFunctionalLocationsInner> installedBases) {
    this.installedBases = installedBases;
    return this;
  }
  /**
  * Add one InstalledBases instance to this {@link CaseReadResponseValue}.
  * @param installedBasesItem The InstalledBases that should be added
  * @return The same instance of type {@link CaseReadResponseValue}
  */
  @Nonnull public CaseReadResponseValue addInstalledBasesItem( @Nonnull final CaseQueryResponseValueInnerFunctionalLocationsInner installedBasesItem) {
    if (this.installedBases == null) {
      this.installedBases = new ArrayList<>();
    }
    this.installedBases.add(installedBasesItem);
    return this;
  }

   /**
   * Get installedBases
   * @return installedBases  The installedBases of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInnerFunctionalLocationsInner> getInstalledBases() {
    return installedBases;
  }

  /**
  * Set the installedBases of this {@link CaseReadResponseValue} instance.
  *
  * @param installedBases  The installedBases of this {@link CaseReadResponseValue}
  */
  public void setInstalledBases( @Nonnull final List<CaseQueryResponseValueInnerFunctionalLocationsInner> installedBases) {
    this.installedBases = installedBases;
  }

   /**
   * Set the account of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param account  The account of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue account(@Nonnull final CaseQueryResponseValueInnerAccount account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account  The account of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerAccount getAccount() {
    return account;
  }

  /**
  * Set the account of this {@link CaseReadResponseValue} instance.
  *
  * @param account  The account of this {@link CaseReadResponseValue}
  */
  public void setAccount( @Nonnull final CaseQueryResponseValueInnerAccount account) {
    this.account = account;
  }

   /**
   * Set the contact of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param contact  The contact of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue contact(@Nonnull final CaseQueryResponseValueInnerContact contact) {
    this.contact = contact;
    return this;
  }

   /**
   * Get contact
   * @return contact  The contact of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerContact getContact() {
    return contact;
  }

  /**
  * Set the contact of this {@link CaseReadResponseValue} instance.
  *
  * @param contact  The contact of this {@link CaseReadResponseValue}
  */
  public void setContact( @Nonnull final CaseQueryResponseValueInnerContact contact) {
    this.contact = contact;
  }

   /**
   * Set the individualCustomer of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param individualCustomer  The individualCustomer of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue individualCustomer(@Nonnull final CaseQueryResponseValueInnerIndividualCustomer individualCustomer) {
    this.individualCustomer = individualCustomer;
    return this;
  }

   /**
   * Get individualCustomer
   * @return individualCustomer  The individualCustomer of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerIndividualCustomer getIndividualCustomer() {
    return individualCustomer;
  }

  /**
  * Set the individualCustomer of this {@link CaseReadResponseValue} instance.
  *
  * @param individualCustomer  The individualCustomer of this {@link CaseReadResponseValue}
  */
  public void setIndividualCustomer( @Nonnull final CaseQueryResponseValueInnerIndividualCustomer individualCustomer) {
    this.individualCustomer = individualCustomer;
  }

   /**
   * Set the processor of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param processor  The processor of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue processor(@Nonnull final CaseQueryResponseValueInnerIndividualCustomer processor) {
    this.processor = processor;
    return this;
  }

   /**
   * Get processor
   * @return processor  The processor of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerIndividualCustomer getProcessor() {
    return processor;
  }

  /**
  * Set the processor of this {@link CaseReadResponseValue} instance.
  *
  * @param processor  The processor of this {@link CaseReadResponseValue}
  */
  public void setProcessor( @Nonnull final CaseQueryResponseValueInnerIndividualCustomer processor) {
    this.processor = processor;
  }

   /**
   * Set the approvers of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param approvers  The approvers of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue approvers(@Nonnull final List<CaseQueryResponseValueInnerIndividualCustomer> approvers) {
    this.approvers = approvers;
    return this;
  }
  /**
  * Add one Approvers instance to this {@link CaseReadResponseValue}.
  * @param approversItem The Approvers that should be added
  * @return The same instance of type {@link CaseReadResponseValue}
  */
  @Nonnull public CaseReadResponseValue addApproversItem( @Nonnull final CaseQueryResponseValueInnerIndividualCustomer approversItem) {
    if (this.approvers == null) {
      this.approvers = new ArrayList<>();
    }
    this.approvers.add(approversItem);
    return this;
  }

   /**
   * Get approvers
   * @return approvers  The approvers of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInnerIndividualCustomer> getApprovers() {
    return approvers;
  }

  /**
  * Set the approvers of this {@link CaseReadResponseValue} instance.
  *
  * @param approvers  The approvers of this {@link CaseReadResponseValue}
  */
  public void setApprovers( @Nonnull final List<CaseQueryResponseValueInnerIndividualCustomer> approvers) {
    this.approvers = approvers;
  }

   /**
   * Set the serviceTeam of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param serviceTeam  The serviceTeam of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue serviceTeam(@Nonnull final CaseQueryResponseValueInnerServiceTeam serviceTeam) {
    this.serviceTeam = serviceTeam;
    return this;
  }

   /**
   * Get serviceTeam
   * @return serviceTeam  The serviceTeam of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerServiceTeam getServiceTeam() {
    return serviceTeam;
  }

  /**
  * Set the serviceTeam of this {@link CaseReadResponseValue} instance.
  *
  * @param serviceTeam  The serviceTeam of this {@link CaseReadResponseValue}
  */
  public void setServiceTeam( @Nonnull final CaseQueryResponseValueInnerServiceTeam serviceTeam) {
    this.serviceTeam = serviceTeam;
  }

   /**
   * Set the description of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param description  The description of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue description(@Nonnull final CaseQueryResponseValueInnerDescription description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description  The description of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerDescription getDescription() {
    return description;
  }

  /**
  * Set the description of this {@link CaseReadResponseValue} instance.
  *
  * @param description  The description of this {@link CaseReadResponseValue}
  */
  public void setDescription( @Nonnull final CaseQueryResponseValueInnerDescription description) {
    this.description = description;
  }

   /**
   * Set the notes of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param notes  The notes of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue notes(@Nonnull final List<CaseQueryResponseValueInnerNotesInner> notes) {
    this.notes = notes;
    return this;
  }
  /**
  * Add one Notes instance to this {@link CaseReadResponseValue}.
  * @param notesItem The Notes that should be added
  * @return The same instance of type {@link CaseReadResponseValue}
  */
  @Nonnull public CaseReadResponseValue addNotesItem( @Nonnull final CaseQueryResponseValueInnerNotesInner notesItem) {
    if (this.notes == null) {
      this.notes = new ArrayList<>();
    }
    this.notes.add(notesItem);
    return this;
  }

   /**
   * Get notes
   * @return notes  The notes of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInnerNotesInner> getNotes() {
    return notes;
  }

  /**
  * Set the notes of this {@link CaseReadResponseValue} instance.
  *
  * @param notes  The notes of this {@link CaseReadResponseValue}
  */
  public void setNotes( @Nonnull final List<CaseQueryResponseValueInnerNotesInner> notes) {
    this.notes = notes;
  }

   /**
   * Set the relatedObjects of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param relatedObjects  The relatedObjects of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue relatedObjects(@Nonnull final List<CaseQueryResponseValueInnerRelatedObjectsInner> relatedObjects) {
    this.relatedObjects = relatedObjects;
    return this;
  }
  /**
  * Add one RelatedObjects instance to this {@link CaseReadResponseValue}.
  * @param relatedObjectsItem The RelatedObjects that should be added
  * @return The same instance of type {@link CaseReadResponseValue}
  */
  @Nonnull public CaseReadResponseValue addRelatedObjectsItem( @Nonnull final CaseQueryResponseValueInnerRelatedObjectsInner relatedObjectsItem) {
    if (this.relatedObjects == null) {
      this.relatedObjects = new ArrayList<>();
    }
    this.relatedObjects.add(relatedObjectsItem);
    return this;
  }

   /**
   * Get relatedObjects
   * @return relatedObjects  The relatedObjects of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInnerRelatedObjectsInner> getRelatedObjects() {
    return relatedObjects;
  }

  /**
  * Set the relatedObjects of this {@link CaseReadResponseValue} instance.
  *
  * @param relatedObjects  The relatedObjects of this {@link CaseReadResponseValue}
  */
  public void setRelatedObjects( @Nonnull final List<CaseQueryResponseValueInnerRelatedObjectsInner> relatedObjects) {
    this.relatedObjects = relatedObjects;
  }

   /**
   * Set the timePoints of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param timePoints  The timePoints of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue timePoints(@Nonnull final CaseReadResponseValueTimePoints timePoints) {
    this.timePoints = timePoints;
    return this;
  }

   /**
   * Get timePoints
   * @return timePoints  The timePoints of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseReadResponseValueTimePoints getTimePoints() {
    return timePoints;
  }

  /**
  * Set the timePoints of this {@link CaseReadResponseValue} instance.
  *
  * @param timePoints  The timePoints of this {@link CaseReadResponseValue}
  */
  public void setTimePoints( @Nonnull final CaseReadResponseValueTimePoints timePoints) {
    this.timePoints = timePoints;
  }

   /**
   * Set the categoryLevel1 of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param categoryLevel1  The categoryLevel1 of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue categoryLevel1(@Nonnull final CaseQueryResponseValueInnerFunctionalLocationsInner categoryLevel1) {
    this.categoryLevel1 = categoryLevel1;
    return this;
  }

   /**
   * Get categoryLevel1
   * @return categoryLevel1  The categoryLevel1 of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerFunctionalLocationsInner getCategoryLevel1() {
    return categoryLevel1;
  }

  /**
  * Set the categoryLevel1 of this {@link CaseReadResponseValue} instance.
  *
  * @param categoryLevel1  The categoryLevel1 of this {@link CaseReadResponseValue}
  */
  public void setCategoryLevel1( @Nonnull final CaseQueryResponseValueInnerFunctionalLocationsInner categoryLevel1) {
    this.categoryLevel1 = categoryLevel1;
  }

   /**
   * Set the categoryLevel2 of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param categoryLevel2  The categoryLevel2 of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue categoryLevel2(@Nonnull final CaseQueryResponseValueInnerFunctionalLocationsInner categoryLevel2) {
    this.categoryLevel2 = categoryLevel2;
    return this;
  }

   /**
   * Get categoryLevel2
   * @return categoryLevel2  The categoryLevel2 of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseQueryResponseValueInnerFunctionalLocationsInner getCategoryLevel2() {
    return categoryLevel2;
  }

  /**
  * Set the categoryLevel2 of this {@link CaseReadResponseValue} instance.
  *
  * @param categoryLevel2  The categoryLevel2 of this {@link CaseReadResponseValue}
  */
  public void setCategoryLevel2( @Nonnull final CaseQueryResponseValueInnerFunctionalLocationsInner categoryLevel2) {
    this.categoryLevel2 = categoryLevel2;
  }

   /**
   * Set the serviceLevelId of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param serviceLevelId  The serviceLevelId of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue serviceLevelId(@Nonnull final UUID serviceLevelId) {
    this.serviceLevelId = serviceLevelId;
    return this;
  }

   /**
   * Get serviceLevelId
   * @return serviceLevelId  The serviceLevelId of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public UUID getServiceLevelId() {
    return serviceLevelId;
  }

  /**
  * Set the serviceLevelId of this {@link CaseReadResponseValue} instance.
  *
  * @param serviceLevelId  The serviceLevelId of this {@link CaseReadResponseValue}
  */
  public void setServiceLevelId( @Nonnull final UUID serviceLevelId) {
    this.serviceLevelId = serviceLevelId;
  }

   /**
   * Set the durationTerms of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param durationTerms  The durationTerms of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue durationTerms(@Nonnull final CaseReadResponseValueDurationTerms durationTerms) {
    this.durationTerms = durationTerms;
    return this;
  }

   /**
   * Get durationTerms
   * @return durationTerms  The durationTerms of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseReadResponseValueDurationTerms getDurationTerms() {
    return durationTerms;
  }

  /**
  * Set the durationTerms of this {@link CaseReadResponseValue} instance.
  *
  * @param durationTerms  The durationTerms of this {@link CaseReadResponseValue}
  */
  public void setDurationTerms( @Nonnull final CaseReadResponseValueDurationTerms durationTerms) {
    this.durationTerms = durationTerms;
  }

   /**
   * Set the isRead of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param isRead  The isRead of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue isRead(@Nonnull final Boolean isRead) {
    this.isRead = isRead;
    return this;
  }

   /**
   * Get isRead
   * @return isRead  The isRead of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public Boolean isIsRead() {
    return isRead;
  }

  /**
  * Set the isRead of this {@link CaseReadResponseValue} instance.
  *
  * @param isRead  The isRead of this {@link CaseReadResponseValue}
  */
  public void setIsRead( @Nonnull final Boolean isRead) {
    this.isRead = isRead;
  }

   /**
   * Set the isEndOfPurpose of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param isEndOfPurpose  The isEndOfPurpose of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue isEndOfPurpose(@Nonnull final Boolean isEndOfPurpose) {
    this.isEndOfPurpose = isEndOfPurpose;
    return this;
  }

   /**
   * Get isEndOfPurpose
   * @return isEndOfPurpose  The isEndOfPurpose of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public Boolean isIsEndOfPurpose() {
    return isEndOfPurpose;
  }

  /**
  * Set the isEndOfPurpose of this {@link CaseReadResponseValue} instance.
  *
  * @param isEndOfPurpose  The isEndOfPurpose of this {@link CaseReadResponseValue}
  */
  public void setIsEndOfPurpose( @Nonnull final Boolean isEndOfPurpose) {
    this.isEndOfPurpose = isEndOfPurpose;
  }

   /**
   * Set the isDepersonalized of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param isDepersonalized  The isDepersonalized of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue isDepersonalized(@Nonnull final Boolean isDepersonalized) {
    this.isDepersonalized = isDepersonalized;
    return this;
  }

   /**
   * Get isDepersonalized
   * @return isDepersonalized  The isDepersonalized of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public Boolean isIsDepersonalized() {
    return isDepersonalized;
  }

  /**
  * Set the isDepersonalized of this {@link CaseReadResponseValue} instance.
  *
  * @param isDepersonalized  The isDepersonalized of this {@link CaseReadResponseValue}
  */
  public void setIsDepersonalized( @Nonnull final Boolean isDepersonalized) {
    this.isDepersonalized = isDepersonalized;
  }

   /**
   * Set the adminData of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param adminData  The adminData of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue adminData(@Nonnull final CaseReadResponseValueAdminData adminData) {
    this.adminData = adminData;
    return this;
  }

   /**
   * Get adminData
   * @return adminData  The adminData of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public CaseReadResponseValueAdminData getAdminData() {
    return adminData;
  }

  /**
  * Set the adminData of this {@link CaseReadResponseValue} instance.
  *
  * @param adminData  The adminData of this {@link CaseReadResponseValue}
  */
  public void setAdminData( @Nonnull final CaseReadResponseValueAdminData adminData) {
    this.adminData = adminData;
  }

   /**
   * Set the extensions of this {@link CaseReadResponseValue} instance and return the same instance.
   *
   * @param extensions  The extensions of this {@link CaseReadResponseValue}
   * @return The same instance of this {@link CaseReadResponseValue} class
   */
   @Nonnull public CaseReadResponseValue extensions(@Nonnull final Object extensions) {
    this.extensions = extensions;
    return this;
  }

   /**
   * Get extensions
   * @return extensions  The extensions of this {@link CaseReadResponseValue} instance.
  **/
  @Nonnull public Object getExtensions() {
    return extensions;
  }

  /**
  * Set the extensions of this {@link CaseReadResponseValue} instance.
  *
  * @param extensions  The extensions of this {@link CaseReadResponseValue}
  */
  public void setExtensions( @Nonnull final Object extensions) {
    this.extensions = extensions;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CaseReadResponseValue}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CaseReadResponseValue}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CaseReadResponseValue has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CaseReadResponseValue caseReadResponseValue = (CaseReadResponseValue) o;
    return Objects.equals(this.cloudSdkCustomFields, caseReadResponseValue.cloudSdkCustomFields) &&
        Objects.equals(this.id, caseReadResponseValue.id) &&
        Objects.equals(this.displayId, caseReadResponseValue.displayId) &&
        Objects.equals(this.subject, caseReadResponseValue.subject) &&
        Objects.equals(this.priority, caseReadResponseValue.priority) &&
        Objects.equals(this.priorityDescription, caseReadResponseValue.priorityDescription) &&
        Objects.equals(this.origin, caseReadResponseValue.origin) &&
        Objects.equals(this.caseType, caseReadResponseValue.caseType) &&
        Objects.equals(this.caseTypeDescription, caseReadResponseValue.caseTypeDescription) &&
        Objects.equals(this.status, caseReadResponseValue.status) &&
        Objects.equals(this.statusDescription, caseReadResponseValue.statusDescription) &&
        Objects.equals(this.escalationStatus, caseReadResponseValue.escalationStatus) &&
        Objects.equals(this.registeredProducts, caseReadResponseValue.registeredProducts) &&
        Objects.equals(this.functionalLocations, caseReadResponseValue.functionalLocations) &&
        Objects.equals(this.productInstallPoints, caseReadResponseValue.productInstallPoints) &&
        Objects.equals(this.installedBases, caseReadResponseValue.installedBases) &&
        Objects.equals(this.account, caseReadResponseValue.account) &&
        Objects.equals(this.contact, caseReadResponseValue.contact) &&
        Objects.equals(this.individualCustomer, caseReadResponseValue.individualCustomer) &&
        Objects.equals(this.processor, caseReadResponseValue.processor) &&
        Objects.equals(this.approvers, caseReadResponseValue.approvers) &&
        Objects.equals(this.serviceTeam, caseReadResponseValue.serviceTeam) &&
        Objects.equals(this.description, caseReadResponseValue.description) &&
        Objects.equals(this.notes, caseReadResponseValue.notes) &&
        Objects.equals(this.relatedObjects, caseReadResponseValue.relatedObjects) &&
        Objects.equals(this.timePoints, caseReadResponseValue.timePoints) &&
        Objects.equals(this.categoryLevel1, caseReadResponseValue.categoryLevel1) &&
        Objects.equals(this.categoryLevel2, caseReadResponseValue.categoryLevel2) &&
        Objects.equals(this.serviceLevelId, caseReadResponseValue.serviceLevelId) &&
        Objects.equals(this.durationTerms, caseReadResponseValue.durationTerms) &&
        Objects.equals(this.isRead, caseReadResponseValue.isRead) &&
        Objects.equals(this.isEndOfPurpose, caseReadResponseValue.isEndOfPurpose) &&
        Objects.equals(this.isDepersonalized, caseReadResponseValue.isDepersonalized) &&
        Objects.equals(this.adminData, caseReadResponseValue.adminData) &&
        Objects.equals(this.extensions, caseReadResponseValue.extensions);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, displayId, subject, priority, priorityDescription, origin, caseType, caseTypeDescription, status, statusDescription, escalationStatus, registeredProducts, functionalLocations, productInstallPoints, installedBases, account, contact, individualCustomer, processor, approvers, serviceTeam, description, notes, relatedObjects, timePoints, categoryLevel1, categoryLevel2, serviceLevelId, durationTerms, isRead, isEndOfPurpose, isDepersonalized, adminData, extensions, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CaseReadResponseValue {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    displayId: ").append(toIndentedString(displayId)).append("\n");
    sb.append("    subject: ").append(toIndentedString(subject)).append("\n");
    sb.append("    priority: ").append(toIndentedString(priority)).append("\n");
    sb.append("    priorityDescription: ").append(toIndentedString(priorityDescription)).append("\n");
    sb.append("    origin: ").append(toIndentedString(origin)).append("\n");
    sb.append("    caseType: ").append(toIndentedString(caseType)).append("\n");
    sb.append("    caseTypeDescription: ").append(toIndentedString(caseTypeDescription)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    statusDescription: ").append(toIndentedString(statusDescription)).append("\n");
    sb.append("    escalationStatus: ").append(toIndentedString(escalationStatus)).append("\n");
    sb.append("    registeredProducts: ").append(toIndentedString(registeredProducts)).append("\n");
    sb.append("    functionalLocations: ").append(toIndentedString(functionalLocations)).append("\n");
    sb.append("    productInstallPoints: ").append(toIndentedString(productInstallPoints)).append("\n");
    sb.append("    installedBases: ").append(toIndentedString(installedBases)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    contact: ").append(toIndentedString(contact)).append("\n");
    sb.append("    individualCustomer: ").append(toIndentedString(individualCustomer)).append("\n");
    sb.append("    processor: ").append(toIndentedString(processor)).append("\n");
    sb.append("    approvers: ").append(toIndentedString(approvers)).append("\n");
    sb.append("    serviceTeam: ").append(toIndentedString(serviceTeam)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    notes: ").append(toIndentedString(notes)).append("\n");
    sb.append("    relatedObjects: ").append(toIndentedString(relatedObjects)).append("\n");
    sb.append("    timePoints: ").append(toIndentedString(timePoints)).append("\n");
    sb.append("    categoryLevel1: ").append(toIndentedString(categoryLevel1)).append("\n");
    sb.append("    categoryLevel2: ").append(toIndentedString(categoryLevel2)).append("\n");
    sb.append("    serviceLevelId: ").append(toIndentedString(serviceLevelId)).append("\n");
    sb.append("    durationTerms: ").append(toIndentedString(durationTerms)).append("\n");
    sb.append("    isRead: ").append(toIndentedString(isRead)).append("\n");
    sb.append("    isEndOfPurpose: ").append(toIndentedString(isEndOfPurpose)).append("\n");
    sb.append("    isDepersonalized: ").append(toIndentedString(isDepersonalized)).append("\n");
    sb.append("    adminData: ").append(toIndentedString(adminData)).append("\n");
    sb.append("    extensions: ").append(toIndentedString(extensions)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

