

/*
 * Case Service
 * Cases are records of service or support requests from an account or individual customer used to track interactions with the requestor. Cases also record details like how much time has passed since the case was created, what actions were taken to resolve the issue, priority or associated products, and much more.  Use this API to view, create, and manage your cases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cnsmodules.model.CaseQueryResponseInfo;
import com.sap.cnsmodules.model.CaseQueryResponseValueInner;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CaseQueryResponse
 */

// CHECKSTYLE:OFF
public class CaseQueryResponse 
// CHECKSTYLE:ON
{
  @JsonProperty("count")
  private Integer count;

  @JsonProperty("value")
  private List<CaseQueryResponseValueInner> value = new ArrayList<>();

  @JsonProperty("info")
  private CaseQueryResponseInfo info;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the count of this {@link CaseQueryResponse} instance and return the same instance.
   *
   * @param count  The count of this {@link CaseQueryResponse}
   * @return The same instance of this {@link CaseQueryResponse} class
   */
   @Nonnull public CaseQueryResponse count(@Nonnull final Integer count) {
    this.count = count;
    return this;
  }

   /**
   * Get count
   * @return count  The count of this {@link CaseQueryResponse} instance.
  **/
  @Nonnull public Integer getCount() {
    return count;
  }

  /**
  * Set the count of this {@link CaseQueryResponse} instance.
  *
  * @param count  The count of this {@link CaseQueryResponse}
  */
  public void setCount( @Nonnull final Integer count) {
    this.count = count;
  }

   /**
   * Set the value of this {@link CaseQueryResponse} instance and return the same instance.
   *
   * @param value  The value of this {@link CaseQueryResponse}
   * @return The same instance of this {@link CaseQueryResponse} class
   */
   @Nonnull public CaseQueryResponse value(@Nonnull final List<CaseQueryResponseValueInner> value) {
    this.value = value;
    return this;
  }
  /**
  * Add one Value instance to this {@link CaseQueryResponse}.
  * @param valueItem The Value that should be added
  * @return The same instance of type {@link CaseQueryResponse}
  */
  @Nonnull public CaseQueryResponse addValueItem( @Nonnull final CaseQueryResponseValueInner valueItem) {
    if (this.value == null) {
      this.value = new ArrayList<>();
    }
    this.value.add(valueItem);
    return this;
  }

   /**
   * Get value
   * @return value  The value of this {@link CaseQueryResponse} instance.
  **/
  @Nonnull public List<CaseQueryResponseValueInner> getValue() {
    return value;
  }

  /**
  * Set the value of this {@link CaseQueryResponse} instance.
  *
  * @param value  The value of this {@link CaseQueryResponse}
  */
  public void setValue( @Nonnull final List<CaseQueryResponseValueInner> value) {
    this.value = value;
  }

   /**
   * Set the info of this {@link CaseQueryResponse} instance and return the same instance.
   *
   * @param info  The info of this {@link CaseQueryResponse}
   * @return The same instance of this {@link CaseQueryResponse} class
   */
   @Nonnull public CaseQueryResponse info(@Nonnull final CaseQueryResponseInfo info) {
    this.info = info;
    return this;
  }

   /**
   * Get info
   * @return info  The info of this {@link CaseQueryResponse} instance.
  **/
  @Nonnull public CaseQueryResponseInfo getInfo() {
    return info;
  }

  /**
  * Set the info of this {@link CaseQueryResponse} instance.
  *
  * @param info  The info of this {@link CaseQueryResponse}
  */
  public void setInfo( @Nonnull final CaseQueryResponseInfo info) {
    this.info = info;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CaseQueryResponse}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CaseQueryResponse}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CaseQueryResponse has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CaseQueryResponse caseQueryResponse = (CaseQueryResponse) o;
    return Objects.equals(this.cloudSdkCustomFields, caseQueryResponse.cloudSdkCustomFields) &&
        Objects.equals(this.count, caseQueryResponse.count) &&
        Objects.equals(this.value, caseQueryResponse.value) &&
        Objects.equals(this.info, caseQueryResponse.info);
  }

  @Override
  public int hashCode() {
    return Objects.hash(count, value, info, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CaseQueryResponse {\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    sb.append("    info: ").append(toIndentedString(info)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

