

/*
 * Case Service
 * Cases are records of service or support requests from an account or individual customer used to track interactions with the requestor. Cases also record details like how much time has passed since the case was created, what actions were taken to resolve the issue, priority or associated products, and much more.  Use this API to view, create, and manage your cases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CaseReadResponseValueTimePoints
 */

// CHECKSTYLE:OFF
public class CaseReadResponseValueTimePoints 
// CHECKSTYLE:ON
{
  @JsonProperty("reportedOn")
  private String reportedOn;

  @JsonProperty("escalatedOn")
  private String escalatedOn;

  @JsonProperty("completedOn")
  private String completedOn;

  @JsonProperty("completionDueOn")
  private String completionDueOn;

  @JsonProperty("assignedToCustomerOn")
  private String assignedToCustomerOn;

  @JsonProperty("assignedToProcessorOn")
  private String assignedToProcessorOn;

  @JsonProperty("initialReviewDueOn")
  private String initialReviewDueOn;

  @JsonProperty("initialReviewCompletedOn")
  private String initialReviewCompletedOn;

  @JsonProperty("resolutionDueOn")
  private String resolutionDueOn;

  @JsonProperty("responseDueOn")
  private String responseDueOn;

  @JsonProperty("closedOn")
  private String closedOn;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the reportedOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param reportedOn  The reportedOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints reportedOn(@Nonnull final String reportedOn) {
    this.reportedOn = reportedOn;
    return this;
  }

   /**
   * Get reportedOn
   * @return reportedOn  The reportedOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getReportedOn() {
    return reportedOn;
  }

  /**
  * Set the reportedOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param reportedOn  The reportedOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setReportedOn( @Nonnull final String reportedOn) {
    this.reportedOn = reportedOn;
  }

   /**
   * Set the escalatedOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param escalatedOn  The escalatedOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints escalatedOn(@Nonnull final String escalatedOn) {
    this.escalatedOn = escalatedOn;
    return this;
  }

   /**
   * Get escalatedOn
   * @return escalatedOn  The escalatedOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getEscalatedOn() {
    return escalatedOn;
  }

  /**
  * Set the escalatedOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param escalatedOn  The escalatedOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setEscalatedOn( @Nonnull final String escalatedOn) {
    this.escalatedOn = escalatedOn;
  }

   /**
   * Set the completedOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param completedOn  The completedOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints completedOn(@Nonnull final String completedOn) {
    this.completedOn = completedOn;
    return this;
  }

   /**
   * Get completedOn
   * @return completedOn  The completedOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getCompletedOn() {
    return completedOn;
  }

  /**
  * Set the completedOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param completedOn  The completedOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setCompletedOn( @Nonnull final String completedOn) {
    this.completedOn = completedOn;
  }

   /**
   * Set the completionDueOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param completionDueOn  The completionDueOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints completionDueOn(@Nonnull final String completionDueOn) {
    this.completionDueOn = completionDueOn;
    return this;
  }

   /**
   * Get completionDueOn
   * @return completionDueOn  The completionDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getCompletionDueOn() {
    return completionDueOn;
  }

  /**
  * Set the completionDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param completionDueOn  The completionDueOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setCompletionDueOn( @Nonnull final String completionDueOn) {
    this.completionDueOn = completionDueOn;
  }

   /**
   * Set the assignedToCustomerOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param assignedToCustomerOn  The assignedToCustomerOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints assignedToCustomerOn(@Nonnull final String assignedToCustomerOn) {
    this.assignedToCustomerOn = assignedToCustomerOn;
    return this;
  }

   /**
   * Get assignedToCustomerOn
   * @return assignedToCustomerOn  The assignedToCustomerOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getAssignedToCustomerOn() {
    return assignedToCustomerOn;
  }

  /**
  * Set the assignedToCustomerOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param assignedToCustomerOn  The assignedToCustomerOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setAssignedToCustomerOn( @Nonnull final String assignedToCustomerOn) {
    this.assignedToCustomerOn = assignedToCustomerOn;
  }

   /**
   * Set the assignedToProcessorOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param assignedToProcessorOn  The assignedToProcessorOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints assignedToProcessorOn(@Nonnull final String assignedToProcessorOn) {
    this.assignedToProcessorOn = assignedToProcessorOn;
    return this;
  }

   /**
   * Get assignedToProcessorOn
   * @return assignedToProcessorOn  The assignedToProcessorOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getAssignedToProcessorOn() {
    return assignedToProcessorOn;
  }

  /**
  * Set the assignedToProcessorOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param assignedToProcessorOn  The assignedToProcessorOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setAssignedToProcessorOn( @Nonnull final String assignedToProcessorOn) {
    this.assignedToProcessorOn = assignedToProcessorOn;
  }

   /**
   * Set the initialReviewDueOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param initialReviewDueOn  The initialReviewDueOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints initialReviewDueOn(@Nonnull final String initialReviewDueOn) {
    this.initialReviewDueOn = initialReviewDueOn;
    return this;
  }

   /**
   * Get initialReviewDueOn
   * @return initialReviewDueOn  The initialReviewDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getInitialReviewDueOn() {
    return initialReviewDueOn;
  }

  /**
  * Set the initialReviewDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param initialReviewDueOn  The initialReviewDueOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setInitialReviewDueOn( @Nonnull final String initialReviewDueOn) {
    this.initialReviewDueOn = initialReviewDueOn;
  }

   /**
   * Set the initialReviewCompletedOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param initialReviewCompletedOn  The initialReviewCompletedOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints initialReviewCompletedOn(@Nonnull final String initialReviewCompletedOn) {
    this.initialReviewCompletedOn = initialReviewCompletedOn;
    return this;
  }

   /**
   * Get initialReviewCompletedOn
   * @return initialReviewCompletedOn  The initialReviewCompletedOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getInitialReviewCompletedOn() {
    return initialReviewCompletedOn;
  }

  /**
  * Set the initialReviewCompletedOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param initialReviewCompletedOn  The initialReviewCompletedOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setInitialReviewCompletedOn( @Nonnull final String initialReviewCompletedOn) {
    this.initialReviewCompletedOn = initialReviewCompletedOn;
  }

   /**
   * Set the resolutionDueOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param resolutionDueOn  The resolutionDueOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints resolutionDueOn(@Nonnull final String resolutionDueOn) {
    this.resolutionDueOn = resolutionDueOn;
    return this;
  }

   /**
   * Get resolutionDueOn
   * @return resolutionDueOn  The resolutionDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getResolutionDueOn() {
    return resolutionDueOn;
  }

  /**
  * Set the resolutionDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param resolutionDueOn  The resolutionDueOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setResolutionDueOn( @Nonnull final String resolutionDueOn) {
    this.resolutionDueOn = resolutionDueOn;
  }

   /**
   * Set the responseDueOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param responseDueOn  The responseDueOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints responseDueOn(@Nonnull final String responseDueOn) {
    this.responseDueOn = responseDueOn;
    return this;
  }

   /**
   * Get responseDueOn
   * @return responseDueOn  The responseDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getResponseDueOn() {
    return responseDueOn;
  }

  /**
  * Set the responseDueOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param responseDueOn  The responseDueOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setResponseDueOn( @Nonnull final String responseDueOn) {
    this.responseDueOn = responseDueOn;
  }

   /**
   * Set the closedOn of this {@link CaseReadResponseValueTimePoints} instance and return the same instance.
   *
   * @param closedOn  The closedOn of this {@link CaseReadResponseValueTimePoints}
   * @return The same instance of this {@link CaseReadResponseValueTimePoints} class
   */
   @Nonnull public CaseReadResponseValueTimePoints closedOn(@Nonnull final String closedOn) {
    this.closedOn = closedOn;
    return this;
  }

   /**
   * Get closedOn
   * @return closedOn  The closedOn of this {@link CaseReadResponseValueTimePoints} instance.
  **/
  @Nonnull public String getClosedOn() {
    return closedOn;
  }

  /**
  * Set the closedOn of this {@link CaseReadResponseValueTimePoints} instance.
  *
  * @param closedOn  The closedOn of this {@link CaseReadResponseValueTimePoints}
  */
  public void setClosedOn( @Nonnull final String closedOn) {
    this.closedOn = closedOn;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CaseReadResponseValueTimePoints}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CaseReadResponseValueTimePoints}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CaseReadResponseValueTimePoints has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CaseReadResponseValueTimePoints caseReadResponseValueTimePoints = (CaseReadResponseValueTimePoints) o;
    return Objects.equals(this.cloudSdkCustomFields, caseReadResponseValueTimePoints.cloudSdkCustomFields) &&
        Objects.equals(this.reportedOn, caseReadResponseValueTimePoints.reportedOn) &&
        Objects.equals(this.escalatedOn, caseReadResponseValueTimePoints.escalatedOn) &&
        Objects.equals(this.completedOn, caseReadResponseValueTimePoints.completedOn) &&
        Objects.equals(this.completionDueOn, caseReadResponseValueTimePoints.completionDueOn) &&
        Objects.equals(this.assignedToCustomerOn, caseReadResponseValueTimePoints.assignedToCustomerOn) &&
        Objects.equals(this.assignedToProcessorOn, caseReadResponseValueTimePoints.assignedToProcessorOn) &&
        Objects.equals(this.initialReviewDueOn, caseReadResponseValueTimePoints.initialReviewDueOn) &&
        Objects.equals(this.initialReviewCompletedOn, caseReadResponseValueTimePoints.initialReviewCompletedOn) &&
        Objects.equals(this.resolutionDueOn, caseReadResponseValueTimePoints.resolutionDueOn) &&
        Objects.equals(this.responseDueOn, caseReadResponseValueTimePoints.responseDueOn) &&
        Objects.equals(this.closedOn, caseReadResponseValueTimePoints.closedOn);
  }

  @Override
  public int hashCode() {
    return Objects.hash(reportedOn, escalatedOn, completedOn, completionDueOn, assignedToCustomerOn, assignedToProcessorOn, initialReviewDueOn, initialReviewCompletedOn, resolutionDueOn, responseDueOn, closedOn, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CaseReadResponseValueTimePoints {\n");
    sb.append("    reportedOn: ").append(toIndentedString(reportedOn)).append("\n");
    sb.append("    escalatedOn: ").append(toIndentedString(escalatedOn)).append("\n");
    sb.append("    completedOn: ").append(toIndentedString(completedOn)).append("\n");
    sb.append("    completionDueOn: ").append(toIndentedString(completionDueOn)).append("\n");
    sb.append("    assignedToCustomerOn: ").append(toIndentedString(assignedToCustomerOn)).append("\n");
    sb.append("    assignedToProcessorOn: ").append(toIndentedString(assignedToProcessorOn)).append("\n");
    sb.append("    initialReviewDueOn: ").append(toIndentedString(initialReviewDueOn)).append("\n");
    sb.append("    initialReviewCompletedOn: ").append(toIndentedString(initialReviewCompletedOn)).append("\n");
    sb.append("    resolutionDueOn: ").append(toIndentedString(resolutionDueOn)).append("\n");
    sb.append("    responseDueOn: ").append(toIndentedString(responseDueOn)).append("\n");
    sb.append("    closedOn: ").append(toIndentedString(closedOn)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

