

/*
 * Case Service
 * Cases are records of service or support requests from an account or individual customer used to track interactions with the requestor. Cases also record details like how much time has passed since the case was created, what actions were taken to resolve the issue, priority or associated products, and much more.  Use this API to view, create, and manage your cases.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cnsmodules.model.CasePutResponseValueAttachmentsInnerAdminData;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * CasePutResponseValueAttachmentsInner
 */

// CHECKSTYLE:OFF
public class CasePutResponseValueAttachmentsInner 
// CHECKSTYLE:ON
{
  @JsonProperty("id")
  private UUID id;

  @JsonProperty("category")
  private String category;

  @JsonProperty("title")
  private String title;

  @JsonProperty("fileName")
  private String fileName;

  @JsonProperty("fileSize")
  private String fileSize;

  @JsonProperty("contentType")
  private String contentType;

  @JsonProperty("status")
  private String status;

  @JsonProperty("adminData")
  private CasePutResponseValueAttachmentsInnerAdminData adminData;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the id of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param id  The id of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner id(@Nonnull final UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id  The id of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public UUID getId() {
    return id;
  }

  /**
  * Set the id of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param id  The id of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setId( @Nonnull final UUID id) {
    this.id = id;
  }

   /**
   * Set the category of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param category  The category of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner category(@Nonnull final String category) {
    this.category = category;
    return this;
  }

   /**
   * Get category
   * @return category  The category of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public String getCategory() {
    return category;
  }

  /**
  * Set the category of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param category  The category of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setCategory( @Nonnull final String category) {
    this.category = category;
  }

   /**
   * Set the title of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param title  The title of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner title(@Nonnull final String title) {
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title  The title of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public String getTitle() {
    return title;
  }

  /**
  * Set the title of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param title  The title of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setTitle( @Nonnull final String title) {
    this.title = title;
  }

   /**
   * Set the fileName of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param fileName  The fileName of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner fileName(@Nonnull final String fileName) {
    this.fileName = fileName;
    return this;
  }

   /**
   * Get fileName
   * @return fileName  The fileName of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public String getFileName() {
    return fileName;
  }

  /**
  * Set the fileName of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param fileName  The fileName of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setFileName( @Nonnull final String fileName) {
    this.fileName = fileName;
  }

   /**
   * Set the fileSize of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param fileSize  The fileSize of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner fileSize(@Nonnull final String fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Get fileSize
   * @return fileSize  The fileSize of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public String getFileSize() {
    return fileSize;
  }

  /**
  * Set the fileSize of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param fileSize  The fileSize of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setFileSize( @Nonnull final String fileSize) {
    this.fileSize = fileSize;
  }

   /**
   * Set the contentType of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param contentType  The contentType of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner contentType(@Nonnull final String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType  The contentType of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public String getContentType() {
    return contentType;
  }

  /**
  * Set the contentType of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param contentType  The contentType of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setContentType( @Nonnull final String contentType) {
    this.contentType = contentType;
  }

   /**
   * Set the status of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param status  The status of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner status(@Nonnull final String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status  The status of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public String getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param status  The status of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setStatus( @Nonnull final String status) {
    this.status = status;
  }

   /**
   * Set the adminData of this {@link CasePutResponseValueAttachmentsInner} instance and return the same instance.
   *
   * @param adminData  The adminData of this {@link CasePutResponseValueAttachmentsInner}
   * @return The same instance of this {@link CasePutResponseValueAttachmentsInner} class
   */
   @Nonnull public CasePutResponseValueAttachmentsInner adminData(@Nonnull final CasePutResponseValueAttachmentsInnerAdminData adminData) {
    this.adminData = adminData;
    return this;
  }

   /**
   * Get adminData
   * @return adminData  The adminData of this {@link CasePutResponseValueAttachmentsInner} instance.
  **/
  @Nonnull public CasePutResponseValueAttachmentsInnerAdminData getAdminData() {
    return adminData;
  }

  /**
  * Set the adminData of this {@link CasePutResponseValueAttachmentsInner} instance.
  *
  * @param adminData  The adminData of this {@link CasePutResponseValueAttachmentsInner}
  */
  public void setAdminData( @Nonnull final CasePutResponseValueAttachmentsInnerAdminData adminData) {
    this.adminData = adminData;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link CasePutResponseValueAttachmentsInner}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link CasePutResponseValueAttachmentsInner}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("CasePutResponseValueAttachmentsInner has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final CasePutResponseValueAttachmentsInner casePutResponseValueAttachmentsInner = (CasePutResponseValueAttachmentsInner) o;
    return Objects.equals(this.cloudSdkCustomFields, casePutResponseValueAttachmentsInner.cloudSdkCustomFields) &&
        Objects.equals(this.id, casePutResponseValueAttachmentsInner.id) &&
        Objects.equals(this.category, casePutResponseValueAttachmentsInner.category) &&
        Objects.equals(this.title, casePutResponseValueAttachmentsInner.title) &&
        Objects.equals(this.fileName, casePutResponseValueAttachmentsInner.fileName) &&
        Objects.equals(this.fileSize, casePutResponseValueAttachmentsInner.fileSize) &&
        Objects.equals(this.contentType, casePutResponseValueAttachmentsInner.contentType) &&
        Objects.equals(this.status, casePutResponseValueAttachmentsInner.status) &&
        Objects.equals(this.adminData, casePutResponseValueAttachmentsInner.adminData);
  }

  @Override
  public int hashCode() {
    return Objects.hash(id, category, title, fileName, fileSize, contentType, status, adminData, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class CasePutResponseValueAttachmentsInner {\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    category: ").append(toIndentedString(category)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    fileName: ").append(toIndentedString(fileName)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    adminData: ").append(toIndentedString(adminData)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

