

/*
 * Registered Product Service
 * The registered product is an instance of a product associated with a customer and generally has a serial ID. Registered product contains information describing its physical location, parties involved, such as the customer or employee responsible, product, and warranty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * RegisteredProductqueryresponseValueInnerRegisteredProductCategory
 */

// CHECKSTYLE:OFF
public class RegisteredProductqueryresponseValueInnerRegisteredProductCategory 
// CHECKSTYLE:ON
{
  @JsonProperty("description")
  private String description;

  @JsonProperty("code")
  private String code;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the description of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} instance and return the same instance.
   *
   * @param description  The description of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerRegisteredProductCategory description(@Nonnull final String description) {
    this.description = description;
    return this;
  }

   /**
   * Get description
   * @return description  The description of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} instance.
  **/
  @Nonnull public String getDescription() {
    return description;
  }

  /**
  * Set the description of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} instance.
  *
  * @param description  The description of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory}
  */
  public void setDescription( @Nonnull final String description) {
    this.description = description;
  }

   /**
   * Set the code of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} instance and return the same instance.
   *
   * @param code  The code of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerRegisteredProductCategory code(@Nonnull final String code) {
    this.code = code;
    return this;
  }

   /**
   * Get code
   * @return code  The code of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} instance.
  **/
  @Nonnull public String getCode() {
    return code;
  }

  /**
  * Set the code of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory} instance.
  *
  * @param code  The code of this {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory}
  */
  public void setCode( @Nonnull final String code) {
    this.code = code;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link RegisteredProductqueryresponseValueInnerRegisteredProductCategory}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("RegisteredProductqueryresponseValueInnerRegisteredProductCategory has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final RegisteredProductqueryresponseValueInnerRegisteredProductCategory registeredProductqueryresponseValueInnerRegisteredProductCategory = (RegisteredProductqueryresponseValueInnerRegisteredProductCategory) o;
    return Objects.equals(this.cloudSdkCustomFields, registeredProductqueryresponseValueInnerRegisteredProductCategory.cloudSdkCustomFields) &&
        Objects.equals(this.description, registeredProductqueryresponseValueInnerRegisteredProductCategory.description) &&
        Objects.equals(this.code, registeredProductqueryresponseValueInnerRegisteredProductCategory.code);
  }

  @Override
  public int hashCode() {
    return Objects.hash(description, code, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredProductqueryresponseValueInnerRegisteredProductCategory {\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

