

/*
 * Registered Product Service
 * The registered product is an instance of a product associated with a customer and generally has a serial ID. Registered product contains information describing its physical location, parties involved, such as the customer or employee responsible, product, and warranty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInner;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * RegisteredProductfile
 */

// CHECKSTYLE:OFF
public class RegisteredProductfile 
// CHECKSTYLE:ON
{
  @JsonProperty("value")
  private RegisteredProductqueryresponseValueInner value;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the value of this {@link RegisteredProductfile} instance and return the same instance.
   *
   * @param value  The value of this {@link RegisteredProductfile}
   * @return The same instance of this {@link RegisteredProductfile} class
   */
   @Nonnull public RegisteredProductfile value(@Nonnull final RegisteredProductqueryresponseValueInner value) {
    this.value = value;
    return this;
  }

   /**
   * Get value
   * @return value  The value of this {@link RegisteredProductfile} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInner getValue() {
    return value;
  }

  /**
  * Set the value of this {@link RegisteredProductfile} instance.
  *
  * @param value  The value of this {@link RegisteredProductfile}
  */
  public void setValue( @Nonnull final RegisteredProductqueryresponseValueInner value) {
    this.value = value;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link RegisteredProductfile}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link RegisteredProductfile}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("RegisteredProductfile has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final RegisteredProductfile registeredProductfile = (RegisteredProductfile) o;
    return Objects.equals(this.cloudSdkCustomFields, registeredProductfile.cloudSdkCustomFields) &&
        Objects.equals(this.value, registeredProductfile.value);
  }

  @Override
  public int hashCode() {
    return Objects.hash(value, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredProductfile {\n");
    sb.append("    value: ").append(toIndentedString(value)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

