

/*
 * Registered Product Service
 * The registered product is an instance of a product associated with a customer and generally has a serial ID. Registered product contains information describing its physical location, parties involved, such as the customer or employee responsible, product, and warranty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.UUID;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * RegisteredProductqueryresponseValueInnerParentRegisteredProduct
 */

// CHECKSTYLE:OFF
public class RegisteredProductqueryresponseValueInnerParentRegisteredProduct 
// CHECKSTYLE:ON
{
  @JsonProperty("displayId")
  private String displayId;

  @JsonProperty("name")
  private String name;

  @JsonProperty("serialId")
  private String serialId;

  @JsonProperty("id")
  private UUID id;

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the displayId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance and return the same instance.
   *
   * @param displayId  The displayId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerParentRegisteredProduct displayId(@Nonnull final String displayId) {
    this.displayId = displayId;
    return this;
  }

   /**
   * Get displayId
   * @return displayId  The displayId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  **/
  @Nonnull public String getDisplayId() {
    return displayId;
  }

  /**
  * Set the displayId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  *
  * @param displayId  The displayId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
  */
  public void setDisplayId( @Nonnull final String displayId) {
    this.displayId = displayId;
  }

   /**
   * Set the name of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance and return the same instance.
   *
   * @param name  The name of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerParentRegisteredProduct name(@Nonnull final String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name  The name of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  **/
  @Nonnull public String getName() {
    return name;
  }

  /**
  * Set the name of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  *
  * @param name  The name of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
  */
  public void setName( @Nonnull final String name) {
    this.name = name;
  }

   /**
   * Set the serialId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance and return the same instance.
   *
   * @param serialId  The serialId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerParentRegisteredProduct serialId(@Nonnull final String serialId) {
    this.serialId = serialId;
    return this;
  }

   /**
   * Get serialId
   * @return serialId  The serialId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  **/
  @Nonnull public String getSerialId() {
    return serialId;
  }

  /**
  * Set the serialId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  *
  * @param serialId  The serialId of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
  */
  public void setSerialId( @Nonnull final String serialId) {
    this.serialId = serialId;
  }

   /**
   * Set the id of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance and return the same instance.
   *
   * @param id  The id of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
   * @return The same instance of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} class
   */
   @Nonnull public RegisteredProductqueryresponseValueInnerParentRegisteredProduct id(@Nonnull final UUID id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id  The id of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  **/
  @Nonnull public UUID getId() {
    return id;
  }

  /**
  * Set the id of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct} instance.
  *
  * @param id  The id of this {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}
  */
  public void setId( @Nonnull final UUID id) {
    this.id = id;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link RegisteredProductqueryresponseValueInnerParentRegisteredProduct}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("RegisteredProductqueryresponseValueInnerParentRegisteredProduct has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final RegisteredProductqueryresponseValueInnerParentRegisteredProduct registeredProductqueryresponseValueInnerParentRegisteredProduct = (RegisteredProductqueryresponseValueInnerParentRegisteredProduct) o;
    return Objects.equals(this.cloudSdkCustomFields, registeredProductqueryresponseValueInnerParentRegisteredProduct.cloudSdkCustomFields) &&
        Objects.equals(this.displayId, registeredProductqueryresponseValueInnerParentRegisteredProduct.displayId) &&
        Objects.equals(this.name, registeredProductqueryresponseValueInnerParentRegisteredProduct.name) &&
        Objects.equals(this.serialId, registeredProductqueryresponseValueInnerParentRegisteredProduct.serialId) &&
        Objects.equals(this.id, registeredProductqueryresponseValueInnerParentRegisteredProduct.id);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayId, name, serialId, id, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredProductqueryresponseValueInnerParentRegisteredProduct {\n");
    sb.append("    displayId: ").append(toIndentedString(displayId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    serialId: ").append(toIndentedString(serialId)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

