

/*
 * Registered Product Service
 * The registered product is an instance of a product associated with a customer and generally has a serial ID. Registered product contains information describing its physical location, parties involved, such as the customer or employee responsible, product, and warranty.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package com.sap.cnsmodules.model;

import java.util.Arrays;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.NoSuchElementException;
import java.util.Objects;
import java.util.Set;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerAccount;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerAddress;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerAdminData;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerDescriptionsInner;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerExternalIdsInner;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerIndividualCustomer;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerParentRegisteredProduct;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerReferenceProduct;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerRegisteredProductCategory;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerServiceTechnician;
import com.sap.cnsmodules.model.RegisteredProductqueryresponseValueInnerWarranty;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.List;
import java.io.Serializable;
import com.fasterxml.jackson.annotation.JsonAnySetter;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;

import javax.annotation.Nonnull;
import javax.annotation.Nullable;

/**
 * RegisteredProductcreaterequest
 */

// CHECKSTYLE:OFF
public class RegisteredProductcreaterequest 
// CHECKSTYLE:ON
{
  @JsonProperty("displayId")
  private String displayId;

  @JsonProperty("externalIds")
  private List<RegisteredProductqueryresponseValueInnerExternalIdsInner> externalIds = new ArrayList<>();

  /**
   * Gets or Sets status
   */
  public enum StatusEnum {
    /**
    * The OBSOLETE option of this RegisteredProductcreaterequest
    */
    OBSOLETE("OBSOLETE"),
    
    /**
    * The BLOCKED option of this RegisteredProductcreaterequest
    */
    BLOCKED("BLOCKED"),
    
    /**
    * The ACTIVE option of this RegisteredProductcreaterequest
    */
    ACTIVE("ACTIVE"),
    
    /**
    * The IN_PREPARATION option of this RegisteredProductcreaterequest
    */
    IN_PREPARATION("IN_PREPARATION");

    private String value;

    StatusEnum(String value) {
      this.value = value;
    }

    /**
    * Get the value of the enum
    * @return The enum value
    */
    @JsonValue
    @Nonnull public String getValue() {
      return value;
    }

    /**
    * Get the String value of the enum value.
    * @return The enum value as String
    */
    @Override
    @Nonnull public String toString() {
      return String.valueOf(value);
    }

    /**
    * Get the enum value from a String value
    * @param value The String value
    * @return The enum value of type RegisteredProductcreaterequest
    */
    @JsonCreator
    @Nonnull public static StatusEnum fromValue(@Nonnull final String value) {
      for (StatusEnum b : StatusEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }
  }

  @JsonProperty("status")
  private StatusEnum status;

  @JsonProperty("account")
  private RegisteredProductqueryresponseValueInnerAccount account;

  @JsonProperty("individualCustomer")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer individualCustomer;

  @JsonProperty("shipToAccount")
  private RegisteredProductqueryresponseValueInnerAccount shipToAccount;

  @JsonProperty("shipToIndividualCustomer")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer shipToIndividualCustomer;

  @JsonProperty("billToAccount")
  private RegisteredProductqueryresponseValueInnerAccount billToAccount;

  @JsonProperty("billToIndividualCustomer")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer billToIndividualCustomer;

  @JsonProperty("payerAccount")
  private RegisteredProductqueryresponseValueInnerAccount payerAccount;

  @JsonProperty("payerIndividualCustomer")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer payerIndividualCustomer;

  @JsonProperty("ownerAccount")
  private RegisteredProductqueryresponseValueInnerAccount ownerAccount;

  @JsonProperty("ownerIndividualCustomer")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer ownerIndividualCustomer;

  @JsonProperty("serviceTechnicianTeam")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer serviceTechnicianTeam;

  @JsonProperty("responsiblePlanner")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer responsiblePlanner;

  @JsonProperty("serviceTechnician")
  private RegisteredProductqueryresponseValueInnerServiceTechnician serviceTechnician;

  @JsonProperty("employeeResponsible")
  private RegisteredProductqueryresponseValueInnerServiceTechnician employeeResponsible;

  @JsonProperty("descriptions")
  private List<RegisteredProductqueryresponseValueInnerDescriptionsInner> descriptions = new ArrayList<>();

  @JsonProperty("address")
  private RegisteredProductqueryresponseValueInnerAddress address;

  @JsonProperty("adminData")
  private RegisteredProductqueryresponseValueInnerAdminData adminData;

  @JsonProperty("registeredProductCategory")
  private RegisteredProductqueryresponseValueInnerRegisteredProductCategory registeredProductCategory;

  @JsonProperty("referenceProduct")
  private RegisteredProductqueryresponseValueInnerReferenceProduct referenceProduct;

  @JsonProperty("parentRegisteredProduct")
  private RegisteredProductqueryresponseValueInnerParentRegisteredProduct parentRegisteredProduct;

  @JsonProperty("parentInstallationPoint")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer parentInstallationPoint;

  @JsonProperty("parentInstalledBase")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer parentInstalledBase;

  @JsonProperty("referenceDate")
  private OffsetDateTime referenceDate;

  @JsonProperty("serialId")
  private String serialId;

  @JsonProperty("warranty")
  private RegisteredProductqueryresponseValueInnerWarranty warranty;

  @JsonProperty("salesOffice")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer salesOffice;

  @JsonProperty("salesGroup")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer salesGroup;

  @JsonProperty("salesOrganisation")
  private RegisteredProductqueryresponseValueInnerIndividualCustomer salesOrganisation;

  @JsonProperty("divisionCode")
  private String divisionCode;

  @JsonProperty("distributionChannelCode")
  private String distributionChannelCode;

  @JsonProperty("internalNotes")
  private List<RegisteredProductqueryresponseValueInnerDescriptionsInner> internalNotes = new ArrayList<>();

  @JsonProperty("customerInformation")
  private List<RegisteredProductqueryresponseValueInnerDescriptionsInner> customerInformation = new ArrayList<>();

  @JsonAnySetter
  private final Map<String, Object> cloudSdkCustomFields = new LinkedHashMap<>();

   /**
   * Set the displayId of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param displayId  The displayId of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest displayId(@Nonnull final String displayId) {
    this.displayId = displayId;
    return this;
  }

   /**
   * Get displayId
   * @return displayId  The displayId of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public String getDisplayId() {
    return displayId;
  }

  /**
  * Set the displayId of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param displayId  The displayId of this {@link RegisteredProductcreaterequest}
  */
  public void setDisplayId( @Nonnull final String displayId) {
    this.displayId = displayId;
  }

   /**
   * Set the externalIds of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param externalIds  The externalIds of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest externalIds(@Nonnull final List<RegisteredProductqueryresponseValueInnerExternalIdsInner> externalIds) {
    this.externalIds = externalIds;
    return this;
  }
  /**
  * Add one ExternalIds instance to this {@link RegisteredProductcreaterequest}.
  * @param externalIdsItem The ExternalIds that should be added
  * @return The same instance of type {@link RegisteredProductcreaterequest}
  */
  @Nonnull public RegisteredProductcreaterequest addExternalIdsItem( @Nonnull final RegisteredProductqueryresponseValueInnerExternalIdsInner externalIdsItem) {
    if (this.externalIds == null) {
      this.externalIds = new ArrayList<>();
    }
    this.externalIds.add(externalIdsItem);
    return this;
  }

   /**
   * Get externalIds
   * @return externalIds  The externalIds of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public List<RegisteredProductqueryresponseValueInnerExternalIdsInner> getExternalIds() {
    return externalIds;
  }

  /**
  * Set the externalIds of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param externalIds  The externalIds of this {@link RegisteredProductcreaterequest}
  */
  public void setExternalIds( @Nonnull final List<RegisteredProductqueryresponseValueInnerExternalIdsInner> externalIds) {
    this.externalIds = externalIds;
  }

   /**
   * Set the status of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param status  The status of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest status(@Nonnull final StatusEnum status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status  The status of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public StatusEnum getStatus() {
    return status;
  }

  /**
  * Set the status of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param status  The status of this {@link RegisteredProductcreaterequest}
  */
  public void setStatus( @Nonnull final StatusEnum status) {
    this.status = status;
  }

   /**
   * Set the account of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param account  The account of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest account(@Nonnull final RegisteredProductqueryresponseValueInnerAccount account) {
    this.account = account;
    return this;
  }

   /**
   * Get account
   * @return account  The account of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerAccount getAccount() {
    return account;
  }

  /**
  * Set the account of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param account  The account of this {@link RegisteredProductcreaterequest}
  */
  public void setAccount( @Nonnull final RegisteredProductqueryresponseValueInnerAccount account) {
    this.account = account;
  }

   /**
   * Set the individualCustomer of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param individualCustomer  The individualCustomer of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest individualCustomer(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer individualCustomer) {
    this.individualCustomer = individualCustomer;
    return this;
  }

   /**
   * Get individualCustomer
   * @return individualCustomer  The individualCustomer of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getIndividualCustomer() {
    return individualCustomer;
  }

  /**
  * Set the individualCustomer of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param individualCustomer  The individualCustomer of this {@link RegisteredProductcreaterequest}
  */
  public void setIndividualCustomer( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer individualCustomer) {
    this.individualCustomer = individualCustomer;
  }

   /**
   * Set the shipToAccount of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param shipToAccount  The shipToAccount of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest shipToAccount(@Nonnull final RegisteredProductqueryresponseValueInnerAccount shipToAccount) {
    this.shipToAccount = shipToAccount;
    return this;
  }

   /**
   * Get shipToAccount
   * @return shipToAccount  The shipToAccount of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerAccount getShipToAccount() {
    return shipToAccount;
  }

  /**
  * Set the shipToAccount of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param shipToAccount  The shipToAccount of this {@link RegisteredProductcreaterequest}
  */
  public void setShipToAccount( @Nonnull final RegisteredProductqueryresponseValueInnerAccount shipToAccount) {
    this.shipToAccount = shipToAccount;
  }

   /**
   * Set the shipToIndividualCustomer of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param shipToIndividualCustomer  The shipToIndividualCustomer of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest shipToIndividualCustomer(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer shipToIndividualCustomer) {
    this.shipToIndividualCustomer = shipToIndividualCustomer;
    return this;
  }

   /**
   * Get shipToIndividualCustomer
   * @return shipToIndividualCustomer  The shipToIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getShipToIndividualCustomer() {
    return shipToIndividualCustomer;
  }

  /**
  * Set the shipToIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param shipToIndividualCustomer  The shipToIndividualCustomer of this {@link RegisteredProductcreaterequest}
  */
  public void setShipToIndividualCustomer( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer shipToIndividualCustomer) {
    this.shipToIndividualCustomer = shipToIndividualCustomer;
  }

   /**
   * Set the billToAccount of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param billToAccount  The billToAccount of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest billToAccount(@Nonnull final RegisteredProductqueryresponseValueInnerAccount billToAccount) {
    this.billToAccount = billToAccount;
    return this;
  }

   /**
   * Get billToAccount
   * @return billToAccount  The billToAccount of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerAccount getBillToAccount() {
    return billToAccount;
  }

  /**
  * Set the billToAccount of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param billToAccount  The billToAccount of this {@link RegisteredProductcreaterequest}
  */
  public void setBillToAccount( @Nonnull final RegisteredProductqueryresponseValueInnerAccount billToAccount) {
    this.billToAccount = billToAccount;
  }

   /**
   * Set the billToIndividualCustomer of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param billToIndividualCustomer  The billToIndividualCustomer of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest billToIndividualCustomer(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer billToIndividualCustomer) {
    this.billToIndividualCustomer = billToIndividualCustomer;
    return this;
  }

   /**
   * Get billToIndividualCustomer
   * @return billToIndividualCustomer  The billToIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getBillToIndividualCustomer() {
    return billToIndividualCustomer;
  }

  /**
  * Set the billToIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param billToIndividualCustomer  The billToIndividualCustomer of this {@link RegisteredProductcreaterequest}
  */
  public void setBillToIndividualCustomer( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer billToIndividualCustomer) {
    this.billToIndividualCustomer = billToIndividualCustomer;
  }

   /**
   * Set the payerAccount of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param payerAccount  The payerAccount of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest payerAccount(@Nonnull final RegisteredProductqueryresponseValueInnerAccount payerAccount) {
    this.payerAccount = payerAccount;
    return this;
  }

   /**
   * Get payerAccount
   * @return payerAccount  The payerAccount of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerAccount getPayerAccount() {
    return payerAccount;
  }

  /**
  * Set the payerAccount of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param payerAccount  The payerAccount of this {@link RegisteredProductcreaterequest}
  */
  public void setPayerAccount( @Nonnull final RegisteredProductqueryresponseValueInnerAccount payerAccount) {
    this.payerAccount = payerAccount;
  }

   /**
   * Set the payerIndividualCustomer of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param payerIndividualCustomer  The payerIndividualCustomer of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest payerIndividualCustomer(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer payerIndividualCustomer) {
    this.payerIndividualCustomer = payerIndividualCustomer;
    return this;
  }

   /**
   * Get payerIndividualCustomer
   * @return payerIndividualCustomer  The payerIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getPayerIndividualCustomer() {
    return payerIndividualCustomer;
  }

  /**
  * Set the payerIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param payerIndividualCustomer  The payerIndividualCustomer of this {@link RegisteredProductcreaterequest}
  */
  public void setPayerIndividualCustomer( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer payerIndividualCustomer) {
    this.payerIndividualCustomer = payerIndividualCustomer;
  }

   /**
   * Set the ownerAccount of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param ownerAccount  The ownerAccount of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest ownerAccount(@Nonnull final RegisteredProductqueryresponseValueInnerAccount ownerAccount) {
    this.ownerAccount = ownerAccount;
    return this;
  }

   /**
   * Get ownerAccount
   * @return ownerAccount  The ownerAccount of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerAccount getOwnerAccount() {
    return ownerAccount;
  }

  /**
  * Set the ownerAccount of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param ownerAccount  The ownerAccount of this {@link RegisteredProductcreaterequest}
  */
  public void setOwnerAccount( @Nonnull final RegisteredProductqueryresponseValueInnerAccount ownerAccount) {
    this.ownerAccount = ownerAccount;
  }

   /**
   * Set the ownerIndividualCustomer of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param ownerIndividualCustomer  The ownerIndividualCustomer of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest ownerIndividualCustomer(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer ownerIndividualCustomer) {
    this.ownerIndividualCustomer = ownerIndividualCustomer;
    return this;
  }

   /**
   * Get ownerIndividualCustomer
   * @return ownerIndividualCustomer  The ownerIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getOwnerIndividualCustomer() {
    return ownerIndividualCustomer;
  }

  /**
  * Set the ownerIndividualCustomer of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param ownerIndividualCustomer  The ownerIndividualCustomer of this {@link RegisteredProductcreaterequest}
  */
  public void setOwnerIndividualCustomer( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer ownerIndividualCustomer) {
    this.ownerIndividualCustomer = ownerIndividualCustomer;
  }

   /**
   * Set the serviceTechnicianTeam of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param serviceTechnicianTeam  The serviceTechnicianTeam of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest serviceTechnicianTeam(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer serviceTechnicianTeam) {
    this.serviceTechnicianTeam = serviceTechnicianTeam;
    return this;
  }

   /**
   * Get serviceTechnicianTeam
   * @return serviceTechnicianTeam  The serviceTechnicianTeam of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getServiceTechnicianTeam() {
    return serviceTechnicianTeam;
  }

  /**
  * Set the serviceTechnicianTeam of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param serviceTechnicianTeam  The serviceTechnicianTeam of this {@link RegisteredProductcreaterequest}
  */
  public void setServiceTechnicianTeam( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer serviceTechnicianTeam) {
    this.serviceTechnicianTeam = serviceTechnicianTeam;
  }

   /**
   * Set the responsiblePlanner of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param responsiblePlanner  The responsiblePlanner of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest responsiblePlanner(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer responsiblePlanner) {
    this.responsiblePlanner = responsiblePlanner;
    return this;
  }

   /**
   * Get responsiblePlanner
   * @return responsiblePlanner  The responsiblePlanner of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getResponsiblePlanner() {
    return responsiblePlanner;
  }

  /**
  * Set the responsiblePlanner of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param responsiblePlanner  The responsiblePlanner of this {@link RegisteredProductcreaterequest}
  */
  public void setResponsiblePlanner( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer responsiblePlanner) {
    this.responsiblePlanner = responsiblePlanner;
  }

   /**
   * Set the serviceTechnician of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param serviceTechnician  The serviceTechnician of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest serviceTechnician(@Nonnull final RegisteredProductqueryresponseValueInnerServiceTechnician serviceTechnician) {
    this.serviceTechnician = serviceTechnician;
    return this;
  }

   /**
   * Get serviceTechnician
   * @return serviceTechnician  The serviceTechnician of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerServiceTechnician getServiceTechnician() {
    return serviceTechnician;
  }

  /**
  * Set the serviceTechnician of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param serviceTechnician  The serviceTechnician of this {@link RegisteredProductcreaterequest}
  */
  public void setServiceTechnician( @Nonnull final RegisteredProductqueryresponseValueInnerServiceTechnician serviceTechnician) {
    this.serviceTechnician = serviceTechnician;
  }

   /**
   * Set the employeeResponsible of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param employeeResponsible  The employeeResponsible of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest employeeResponsible(@Nonnull final RegisteredProductqueryresponseValueInnerServiceTechnician employeeResponsible) {
    this.employeeResponsible = employeeResponsible;
    return this;
  }

   /**
   * Get employeeResponsible
   * @return employeeResponsible  The employeeResponsible of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerServiceTechnician getEmployeeResponsible() {
    return employeeResponsible;
  }

  /**
  * Set the employeeResponsible of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param employeeResponsible  The employeeResponsible of this {@link RegisteredProductcreaterequest}
  */
  public void setEmployeeResponsible( @Nonnull final RegisteredProductqueryresponseValueInnerServiceTechnician employeeResponsible) {
    this.employeeResponsible = employeeResponsible;
  }

   /**
   * Set the descriptions of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param descriptions  The descriptions of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest descriptions(@Nonnull final List<RegisteredProductqueryresponseValueInnerDescriptionsInner> descriptions) {
    this.descriptions = descriptions;
    return this;
  }
  /**
  * Add one Descriptions instance to this {@link RegisteredProductcreaterequest}.
  * @param descriptionsItem The Descriptions that should be added
  * @return The same instance of type {@link RegisteredProductcreaterequest}
  */
  @Nonnull public RegisteredProductcreaterequest addDescriptionsItem( @Nonnull final RegisteredProductqueryresponseValueInnerDescriptionsInner descriptionsItem) {
    if (this.descriptions == null) {
      this.descriptions = new ArrayList<>();
    }
    this.descriptions.add(descriptionsItem);
    return this;
  }

   /**
   * Get descriptions
   * @return descriptions  The descriptions of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public List<RegisteredProductqueryresponseValueInnerDescriptionsInner> getDescriptions() {
    return descriptions;
  }

  /**
  * Set the descriptions of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param descriptions  The descriptions of this {@link RegisteredProductcreaterequest}
  */
  public void setDescriptions( @Nonnull final List<RegisteredProductqueryresponseValueInnerDescriptionsInner> descriptions) {
    this.descriptions = descriptions;
  }

   /**
   * Set the address of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param address  The address of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest address(@Nonnull final RegisteredProductqueryresponseValueInnerAddress address) {
    this.address = address;
    return this;
  }

   /**
   * Get address
   * @return address  The address of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerAddress getAddress() {
    return address;
  }

  /**
  * Set the address of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param address  The address of this {@link RegisteredProductcreaterequest}
  */
  public void setAddress( @Nonnull final RegisteredProductqueryresponseValueInnerAddress address) {
    this.address = address;
  }

   /**
   * Set the adminData of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param adminData  The adminData of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest adminData(@Nonnull final RegisteredProductqueryresponseValueInnerAdminData adminData) {
    this.adminData = adminData;
    return this;
  }

   /**
   * Get adminData
   * @return adminData  The adminData of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerAdminData getAdminData() {
    return adminData;
  }

  /**
  * Set the adminData of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param adminData  The adminData of this {@link RegisteredProductcreaterequest}
  */
  public void setAdminData( @Nonnull final RegisteredProductqueryresponseValueInnerAdminData adminData) {
    this.adminData = adminData;
  }

   /**
   * Set the registeredProductCategory of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param registeredProductCategory  The registeredProductCategory of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest registeredProductCategory(@Nonnull final RegisteredProductqueryresponseValueInnerRegisteredProductCategory registeredProductCategory) {
    this.registeredProductCategory = registeredProductCategory;
    return this;
  }

   /**
   * Get registeredProductCategory
   * @return registeredProductCategory  The registeredProductCategory of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerRegisteredProductCategory getRegisteredProductCategory() {
    return registeredProductCategory;
  }

  /**
  * Set the registeredProductCategory of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param registeredProductCategory  The registeredProductCategory of this {@link RegisteredProductcreaterequest}
  */
  public void setRegisteredProductCategory( @Nonnull final RegisteredProductqueryresponseValueInnerRegisteredProductCategory registeredProductCategory) {
    this.registeredProductCategory = registeredProductCategory;
  }

   /**
   * Set the referenceProduct of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param referenceProduct  The referenceProduct of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest referenceProduct(@Nonnull final RegisteredProductqueryresponseValueInnerReferenceProduct referenceProduct) {
    this.referenceProduct = referenceProduct;
    return this;
  }

   /**
   * Get referenceProduct
   * @return referenceProduct  The referenceProduct of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerReferenceProduct getReferenceProduct() {
    return referenceProduct;
  }

  /**
  * Set the referenceProduct of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param referenceProduct  The referenceProduct of this {@link RegisteredProductcreaterequest}
  */
  public void setReferenceProduct( @Nonnull final RegisteredProductqueryresponseValueInnerReferenceProduct referenceProduct) {
    this.referenceProduct = referenceProduct;
  }

   /**
   * Set the parentRegisteredProduct of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param parentRegisteredProduct  The parentRegisteredProduct of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest parentRegisteredProduct(@Nonnull final RegisteredProductqueryresponseValueInnerParentRegisteredProduct parentRegisteredProduct) {
    this.parentRegisteredProduct = parentRegisteredProduct;
    return this;
  }

   /**
   * Get parentRegisteredProduct
   * @return parentRegisteredProduct  The parentRegisteredProduct of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerParentRegisteredProduct getParentRegisteredProduct() {
    return parentRegisteredProduct;
  }

  /**
  * Set the parentRegisteredProduct of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param parentRegisteredProduct  The parentRegisteredProduct of this {@link RegisteredProductcreaterequest}
  */
  public void setParentRegisteredProduct( @Nonnull final RegisteredProductqueryresponseValueInnerParentRegisteredProduct parentRegisteredProduct) {
    this.parentRegisteredProduct = parentRegisteredProduct;
  }

   /**
   * Set the parentInstallationPoint of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param parentInstallationPoint  The parentInstallationPoint of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest parentInstallationPoint(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer parentInstallationPoint) {
    this.parentInstallationPoint = parentInstallationPoint;
    return this;
  }

   /**
   * Get parentInstallationPoint
   * @return parentInstallationPoint  The parentInstallationPoint of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getParentInstallationPoint() {
    return parentInstallationPoint;
  }

  /**
  * Set the parentInstallationPoint of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param parentInstallationPoint  The parentInstallationPoint of this {@link RegisteredProductcreaterequest}
  */
  public void setParentInstallationPoint( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer parentInstallationPoint) {
    this.parentInstallationPoint = parentInstallationPoint;
  }

   /**
   * Set the parentInstalledBase of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param parentInstalledBase  The parentInstalledBase of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest parentInstalledBase(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer parentInstalledBase) {
    this.parentInstalledBase = parentInstalledBase;
    return this;
  }

   /**
   * Get parentInstalledBase
   * @return parentInstalledBase  The parentInstalledBase of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getParentInstalledBase() {
    return parentInstalledBase;
  }

  /**
  * Set the parentInstalledBase of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param parentInstalledBase  The parentInstalledBase of this {@link RegisteredProductcreaterequest}
  */
  public void setParentInstalledBase( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer parentInstalledBase) {
    this.parentInstalledBase = parentInstalledBase;
  }

   /**
   * Set the referenceDate of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param referenceDate  The referenceDate of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest referenceDate(@Nonnull final OffsetDateTime referenceDate) {
    this.referenceDate = referenceDate;
    return this;
  }

   /**
   * Get referenceDate
   * @return referenceDate  The referenceDate of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public OffsetDateTime getReferenceDate() {
    return referenceDate;
  }

  /**
  * Set the referenceDate of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param referenceDate  The referenceDate of this {@link RegisteredProductcreaterequest}
  */
  public void setReferenceDate( @Nonnull final OffsetDateTime referenceDate) {
    this.referenceDate = referenceDate;
  }

   /**
   * Set the serialId of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param serialId  The serialId of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest serialId(@Nonnull final String serialId) {
    this.serialId = serialId;
    return this;
  }

   /**
   * Get serialId
   * @return serialId  The serialId of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public String getSerialId() {
    return serialId;
  }

  /**
  * Set the serialId of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param serialId  The serialId of this {@link RegisteredProductcreaterequest}
  */
  public void setSerialId( @Nonnull final String serialId) {
    this.serialId = serialId;
  }

   /**
   * Set the warranty of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param warranty  The warranty of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest warranty(@Nonnull final RegisteredProductqueryresponseValueInnerWarranty warranty) {
    this.warranty = warranty;
    return this;
  }

   /**
   * Get warranty
   * @return warranty  The warranty of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerWarranty getWarranty() {
    return warranty;
  }

  /**
  * Set the warranty of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param warranty  The warranty of this {@link RegisteredProductcreaterequest}
  */
  public void setWarranty( @Nonnull final RegisteredProductqueryresponseValueInnerWarranty warranty) {
    this.warranty = warranty;
  }

   /**
   * Set the salesOffice of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param salesOffice  The salesOffice of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest salesOffice(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer salesOffice) {
    this.salesOffice = salesOffice;
    return this;
  }

   /**
   * Get salesOffice
   * @return salesOffice  The salesOffice of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getSalesOffice() {
    return salesOffice;
  }

  /**
  * Set the salesOffice of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param salesOffice  The salesOffice of this {@link RegisteredProductcreaterequest}
  */
  public void setSalesOffice( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer salesOffice) {
    this.salesOffice = salesOffice;
  }

   /**
   * Set the salesGroup of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param salesGroup  The salesGroup of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest salesGroup(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer salesGroup) {
    this.salesGroup = salesGroup;
    return this;
  }

   /**
   * Get salesGroup
   * @return salesGroup  The salesGroup of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getSalesGroup() {
    return salesGroup;
  }

  /**
  * Set the salesGroup of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param salesGroup  The salesGroup of this {@link RegisteredProductcreaterequest}
  */
  public void setSalesGroup( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer salesGroup) {
    this.salesGroup = salesGroup;
  }

   /**
   * Set the salesOrganisation of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param salesOrganisation  The salesOrganisation of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest salesOrganisation(@Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer salesOrganisation) {
    this.salesOrganisation = salesOrganisation;
    return this;
  }

   /**
   * Get salesOrganisation
   * @return salesOrganisation  The salesOrganisation of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public RegisteredProductqueryresponseValueInnerIndividualCustomer getSalesOrganisation() {
    return salesOrganisation;
  }

  /**
  * Set the salesOrganisation of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param salesOrganisation  The salesOrganisation of this {@link RegisteredProductcreaterequest}
  */
  public void setSalesOrganisation( @Nonnull final RegisteredProductqueryresponseValueInnerIndividualCustomer salesOrganisation) {
    this.salesOrganisation = salesOrganisation;
  }

   /**
   * Set the divisionCode of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param divisionCode  The divisionCode of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest divisionCode(@Nonnull final String divisionCode) {
    this.divisionCode = divisionCode;
    return this;
  }

   /**
   * Get divisionCode
   * @return divisionCode  The divisionCode of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public String getDivisionCode() {
    return divisionCode;
  }

  /**
  * Set the divisionCode of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param divisionCode  The divisionCode of this {@link RegisteredProductcreaterequest}
  */
  public void setDivisionCode( @Nonnull final String divisionCode) {
    this.divisionCode = divisionCode;
  }

   /**
   * Set the distributionChannelCode of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param distributionChannelCode  The distributionChannelCode of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest distributionChannelCode(@Nonnull final String distributionChannelCode) {
    this.distributionChannelCode = distributionChannelCode;
    return this;
  }

   /**
   * Get distributionChannelCode
   * @return distributionChannelCode  The distributionChannelCode of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public String getDistributionChannelCode() {
    return distributionChannelCode;
  }

  /**
  * Set the distributionChannelCode of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param distributionChannelCode  The distributionChannelCode of this {@link RegisteredProductcreaterequest}
  */
  public void setDistributionChannelCode( @Nonnull final String distributionChannelCode) {
    this.distributionChannelCode = distributionChannelCode;
  }

   /**
   * Set the internalNotes of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param internalNotes  The internalNotes of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest internalNotes(@Nonnull final List<RegisteredProductqueryresponseValueInnerDescriptionsInner> internalNotes) {
    this.internalNotes = internalNotes;
    return this;
  }
  /**
  * Add one InternalNotes instance to this {@link RegisteredProductcreaterequest}.
  * @param internalNotesItem The InternalNotes that should be added
  * @return The same instance of type {@link RegisteredProductcreaterequest}
  */
  @Nonnull public RegisteredProductcreaterequest addInternalNotesItem( @Nonnull final RegisteredProductqueryresponseValueInnerDescriptionsInner internalNotesItem) {
    if (this.internalNotes == null) {
      this.internalNotes = new ArrayList<>();
    }
    this.internalNotes.add(internalNotesItem);
    return this;
  }

   /**
   * Get internalNotes
   * @return internalNotes  The internalNotes of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public List<RegisteredProductqueryresponseValueInnerDescriptionsInner> getInternalNotes() {
    return internalNotes;
  }

  /**
  * Set the internalNotes of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param internalNotes  The internalNotes of this {@link RegisteredProductcreaterequest}
  */
  public void setInternalNotes( @Nonnull final List<RegisteredProductqueryresponseValueInnerDescriptionsInner> internalNotes) {
    this.internalNotes = internalNotes;
  }

   /**
   * Set the customerInformation of this {@link RegisteredProductcreaterequest} instance and return the same instance.
   *
   * @param customerInformation  The customerInformation of this {@link RegisteredProductcreaterequest}
   * @return The same instance of this {@link RegisteredProductcreaterequest} class
   */
   @Nonnull public RegisteredProductcreaterequest customerInformation(@Nonnull final List<RegisteredProductqueryresponseValueInnerDescriptionsInner> customerInformation) {
    this.customerInformation = customerInformation;
    return this;
  }
  /**
  * Add one CustomerInformation instance to this {@link RegisteredProductcreaterequest}.
  * @param customerInformationItem The CustomerInformation that should be added
  * @return The same instance of type {@link RegisteredProductcreaterequest}
  */
  @Nonnull public RegisteredProductcreaterequest addCustomerInformationItem( @Nonnull final RegisteredProductqueryresponseValueInnerDescriptionsInner customerInformationItem) {
    if (this.customerInformation == null) {
      this.customerInformation = new ArrayList<>();
    }
    this.customerInformation.add(customerInformationItem);
    return this;
  }

   /**
   * Get customerInformation
   * @return customerInformation  The customerInformation of this {@link RegisteredProductcreaterequest} instance.
  **/
  @Nonnull public List<RegisteredProductqueryresponseValueInnerDescriptionsInner> getCustomerInformation() {
    return customerInformation;
  }

  /**
  * Set the customerInformation of this {@link RegisteredProductcreaterequest} instance.
  *
  * @param customerInformation  The customerInformation of this {@link RegisteredProductcreaterequest}
  */
  public void setCustomerInformation( @Nonnull final List<RegisteredProductqueryresponseValueInnerDescriptionsInner> customerInformation) {
    this.customerInformation = customerInformation;
  }

  /**
   * Get the names of the unrecognizable properties of the {@link RegisteredProductcreaterequest}.
   * @return The set of properties names
   */
  @Nonnull
  public Set<String> getCustomFieldNames() {
    return cloudSdkCustomFields.keySet();
  }

  /**
   * Get the value of an unrecognizable property of the {@link RegisteredProductcreaterequest}.
   * @param name  The name of the property
   * @return The value of the property
   * @throws NoSuchElementException  If no property with the given name could be found.
   */
  @Nullable
  public Object getCustomField(@Nonnull final String name) throws NoSuchElementException {
    if( !cloudSdkCustomFields.containsKey(name) ) {
        throw new NoSuchElementException("RegisteredProductcreaterequest has no field with name '" + name + "'.");
    }
    return cloudSdkCustomFields.get(name);
  }

  @Override
  public boolean equals(@Nullable final java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    final RegisteredProductcreaterequest registeredProductcreaterequest = (RegisteredProductcreaterequest) o;
    return Objects.equals(this.cloudSdkCustomFields, registeredProductcreaterequest.cloudSdkCustomFields) &&
        Objects.equals(this.displayId, registeredProductcreaterequest.displayId) &&
        Objects.equals(this.externalIds, registeredProductcreaterequest.externalIds) &&
        Objects.equals(this.status, registeredProductcreaterequest.status) &&
        Objects.equals(this.account, registeredProductcreaterequest.account) &&
        Objects.equals(this.individualCustomer, registeredProductcreaterequest.individualCustomer) &&
        Objects.equals(this.shipToAccount, registeredProductcreaterequest.shipToAccount) &&
        Objects.equals(this.shipToIndividualCustomer, registeredProductcreaterequest.shipToIndividualCustomer) &&
        Objects.equals(this.billToAccount, registeredProductcreaterequest.billToAccount) &&
        Objects.equals(this.billToIndividualCustomer, registeredProductcreaterequest.billToIndividualCustomer) &&
        Objects.equals(this.payerAccount, registeredProductcreaterequest.payerAccount) &&
        Objects.equals(this.payerIndividualCustomer, registeredProductcreaterequest.payerIndividualCustomer) &&
        Objects.equals(this.ownerAccount, registeredProductcreaterequest.ownerAccount) &&
        Objects.equals(this.ownerIndividualCustomer, registeredProductcreaterequest.ownerIndividualCustomer) &&
        Objects.equals(this.serviceTechnicianTeam, registeredProductcreaterequest.serviceTechnicianTeam) &&
        Objects.equals(this.responsiblePlanner, registeredProductcreaterequest.responsiblePlanner) &&
        Objects.equals(this.serviceTechnician, registeredProductcreaterequest.serviceTechnician) &&
        Objects.equals(this.employeeResponsible, registeredProductcreaterequest.employeeResponsible) &&
        Objects.equals(this.descriptions, registeredProductcreaterequest.descriptions) &&
        Objects.equals(this.address, registeredProductcreaterequest.address) &&
        Objects.equals(this.adminData, registeredProductcreaterequest.adminData) &&
        Objects.equals(this.registeredProductCategory, registeredProductcreaterequest.registeredProductCategory) &&
        Objects.equals(this.referenceProduct, registeredProductcreaterequest.referenceProduct) &&
        Objects.equals(this.parentRegisteredProduct, registeredProductcreaterequest.parentRegisteredProduct) &&
        Objects.equals(this.parentInstallationPoint, registeredProductcreaterequest.parentInstallationPoint) &&
        Objects.equals(this.parentInstalledBase, registeredProductcreaterequest.parentInstalledBase) &&
        Objects.equals(this.referenceDate, registeredProductcreaterequest.referenceDate) &&
        Objects.equals(this.serialId, registeredProductcreaterequest.serialId) &&
        Objects.equals(this.warranty, registeredProductcreaterequest.warranty) &&
        Objects.equals(this.salesOffice, registeredProductcreaterequest.salesOffice) &&
        Objects.equals(this.salesGroup, registeredProductcreaterequest.salesGroup) &&
        Objects.equals(this.salesOrganisation, registeredProductcreaterequest.salesOrganisation) &&
        Objects.equals(this.divisionCode, registeredProductcreaterequest.divisionCode) &&
        Objects.equals(this.distributionChannelCode, registeredProductcreaterequest.distributionChannelCode) &&
        Objects.equals(this.internalNotes, registeredProductcreaterequest.internalNotes) &&
        Objects.equals(this.customerInformation, registeredProductcreaterequest.customerInformation);
  }

  @Override
  public int hashCode() {
    return Objects.hash(displayId, externalIds, status, account, individualCustomer, shipToAccount, shipToIndividualCustomer, billToAccount, billToIndividualCustomer, payerAccount, payerIndividualCustomer, ownerAccount, ownerIndividualCustomer, serviceTechnicianTeam, responsiblePlanner, serviceTechnician, employeeResponsible, descriptions, address, adminData, registeredProductCategory, referenceProduct, parentRegisteredProduct, parentInstallationPoint, parentInstalledBase, referenceDate, serialId, warranty, salesOffice, salesGroup, salesOrganisation, divisionCode, distributionChannelCode, internalNotes, customerInformation, cloudSdkCustomFields);
  }

  @Override
  @Nonnull public String toString() {
    final StringBuilder sb = new StringBuilder();
    sb.append("class RegisteredProductcreaterequest {\n");
    sb.append("    displayId: ").append(toIndentedString(displayId)).append("\n");
    sb.append("    externalIds: ").append(toIndentedString(externalIds)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    account: ").append(toIndentedString(account)).append("\n");
    sb.append("    individualCustomer: ").append(toIndentedString(individualCustomer)).append("\n");
    sb.append("    shipToAccount: ").append(toIndentedString(shipToAccount)).append("\n");
    sb.append("    shipToIndividualCustomer: ").append(toIndentedString(shipToIndividualCustomer)).append("\n");
    sb.append("    billToAccount: ").append(toIndentedString(billToAccount)).append("\n");
    sb.append("    billToIndividualCustomer: ").append(toIndentedString(billToIndividualCustomer)).append("\n");
    sb.append("    payerAccount: ").append(toIndentedString(payerAccount)).append("\n");
    sb.append("    payerIndividualCustomer: ").append(toIndentedString(payerIndividualCustomer)).append("\n");
    sb.append("    ownerAccount: ").append(toIndentedString(ownerAccount)).append("\n");
    sb.append("    ownerIndividualCustomer: ").append(toIndentedString(ownerIndividualCustomer)).append("\n");
    sb.append("    serviceTechnicianTeam: ").append(toIndentedString(serviceTechnicianTeam)).append("\n");
    sb.append("    responsiblePlanner: ").append(toIndentedString(responsiblePlanner)).append("\n");
    sb.append("    serviceTechnician: ").append(toIndentedString(serviceTechnician)).append("\n");
    sb.append("    employeeResponsible: ").append(toIndentedString(employeeResponsible)).append("\n");
    sb.append("    descriptions: ").append(toIndentedString(descriptions)).append("\n");
    sb.append("    address: ").append(toIndentedString(address)).append("\n");
    sb.append("    adminData: ").append(toIndentedString(adminData)).append("\n");
    sb.append("    registeredProductCategory: ").append(toIndentedString(registeredProductCategory)).append("\n");
    sb.append("    referenceProduct: ").append(toIndentedString(referenceProduct)).append("\n");
    sb.append("    parentRegisteredProduct: ").append(toIndentedString(parentRegisteredProduct)).append("\n");
    sb.append("    parentInstallationPoint: ").append(toIndentedString(parentInstallationPoint)).append("\n");
    sb.append("    parentInstalledBase: ").append(toIndentedString(parentInstalledBase)).append("\n");
    sb.append("    referenceDate: ").append(toIndentedString(referenceDate)).append("\n");
    sb.append("    serialId: ").append(toIndentedString(serialId)).append("\n");
    sb.append("    warranty: ").append(toIndentedString(warranty)).append("\n");
    sb.append("    salesOffice: ").append(toIndentedString(salesOffice)).append("\n");
    sb.append("    salesGroup: ").append(toIndentedString(salesGroup)).append("\n");
    sb.append("    salesOrganisation: ").append(toIndentedString(salesOrganisation)).append("\n");
    sb.append("    divisionCode: ").append(toIndentedString(divisionCode)).append("\n");
    sb.append("    distributionChannelCode: ").append(toIndentedString(distributionChannelCode)).append("\n");
    sb.append("    internalNotes: ").append(toIndentedString(internalNotes)).append("\n");
    sb.append("    customerInformation: ").append(toIndentedString(customerInformation)).append("\n");
    cloudSdkCustomFields.forEach((k,v) -> sb.append("    ").append(k).append(": ").append(toIndentedString(v)).append("\n"));
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(final java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

